### ISSUE TITLE
the database operation too slow

### ISSUE THREAD

**Issue by shmilyoo** [dfahlander/Dexie.js#1021]
such as Table.add()， Collection.toArray()

```
const a = await db.myTable.where('timestamp').below(now);   // this cost below 1ms
const b = await db.myTable.where('timestamp').below(now).toArray();  // This line takes too long, often it's 1-3 seconds
```

the data row like this:
`{"type":3,"data":{"source":2,"type":0,"id":68,"x":140,"y":738},"timestamp":1587103463524,"session":"08ffc8e1-5a7e-4100-ba92-ecf74e788435","id":125095}`

Is this due to the asynchronous internal mechanism of indexedDB?

**Comment by dfahlander** [comment]
The first line does not need to be awaited as it does return a Promise. If is fast by definition as no request has been made.

The second line will execute the request. If it takes 1-3 seconds, I believe it is due to the amount of data returned is large. There is not much Dexie-specific code in these samples that takes time. Internally Dexie will call IDBIndex.getAll(IDBKeyRange.upperBound(now)). This is the most optimal way to execute the query. If that still takes time, it could only be due to how much data is being returned.

**Comment by shmilyoo** [comment]
> The first line does not need to be awaited as it does return a Promise. If is fast by definition as no request has been made.
> 
> The second line will execute the request. If it takes 1-3 seconds, I believe it is due to the amount of data returned is large. There is not much Dexie-specific code in these samples that takes time. Internally Dexie will call IDBIndex.getAll(IDBKeyRange.upperBound(now)). This is the most optimal way to execute the query. If that still takes time, it could only be due to how much data is being returned.

I cleared the indexedDB table. 
and then the only line `const b = await db.myTable.where('timestamp').below(now).toArray();`, it takes anywhere from a few dozen to a few hundred milliseconds. Many 300-800ms results are unacceptable.

**Comment by dfahlander** [comment]
Are you sure you are measuring that call only? In case the database needs to open, the open call will take place in order to do the query. This happens lazily.
Make sure you are measuring the query only by first awaiting db.open(). Then start measuring the toArray() call.

```js
await db.open();
// Start measuring here when db is open:
const tick = performance.now();
const b = await db.myTable.where('timestamp').below(now).toArray();
const tock = performance.now();
console.log(tock - tick);
```

I'm pretty sure you won't see any big difference from the native api.

**Comment by shmilyoo** [comment]
Is db.open() a must? I see the documentation is direct db=new Dexie(...) .
Do users need to manually call db.open() again?

**Comment by dfahlander** [comment]
@shmilyoo No, it's optional, but it needs to be done under the hood if it wasn't explicitely called. So if you are measuring query performance, you should do it and await it before you start measuring the queries. You should keep the db open during you entire app lifetime - this is handled automatically for you (unless you explicitely close/reopen the db for every request, which would be a performance issue).

**Comment by shmilyoo** [comment]
@dfahlander 
I stopped the other operations on the database and compared the search operations with different database content sizes.
You're right, the timing of this has to do with the size of the content.
I will close this issue
