### ISSUE TITLE
Error trying to apply upgrade function and object store deletion in same version

### ISSUE THREAD

**Issue by chrahunt** [dfahlander/Dexie.js#105]
This may be related to #1, but I think it's narrow enough in scope to warrant a different issue. This is in a Chrome extension so the IE bug is not relevant.

I have an existing database that I'm trying to use with Dexie. In the new version I need to remove a few data stores and run an upgrade function. The data from the data stores to be removed is used in the upgrade function. Based on the order that functions are applied in the version upgrade queue defined in [this](https://github.com/dfahlander/Dexie.js/blob/666f641cd6786a0ad3fe7b9879973ead527ac99f/src/Dexie.js#L182) function, it looks like the object stores are going to be deleted after the upgrade function is applied, so this shouldn't be a problem.

Existing object stores can be removed by setting the key name to `null` in the object passed to the `stores` instance method, but when I do that I receive an error on [this](https://github.com/dfahlander/Dexie.js/blob/666f641cd6786a0ad3fe7b9879973ead527ac99f/src/Dexie.js#L394) line because the tableSchemas for the transaction are only being derived from the current version, which now omits the previous store schemas.

I have a failing test on [this](https://github.com/chrahunt/Dexie.js/tree/delete-and-upgrade) branch. I can work on a fix later today, but I wanted to make sure I'm not missing some detail that would be necessary to use these to-be-deleted object stores in the upgrade function.

**Comment by dfahlander** [comment]
Thanks for detailed explanation! I'm sure this is a bug indeed. Deep in my mind I recall that this is an unsupported and untested use case. Would be great if you did find a solution for it, please go ahead. And thanks muc!

**Comment by dfahlander** [comment]
I saw you have a fix in that branch. Please do a pull request when you feel comfortable with it.

I tried to run the [test suite](https://rawgit.com/chrahunt/Dexie.js/delete-and-upgrade/test/run-unit-tests.html). It worked for all tests but [this one](https://rawgit.com/chrahunt/Dexie.js/delete-and-upgrade/test/run-unit-tests.html?testNumber=76). Seems to be a trivial issue that I could look at if you do a pull request.

**Comment by chrahunt** [comment]
Working on this again after rebasing on master. I think there's a little more to this that isn't currently being tested (ensuring only applicable object store names are available on transaction at upgrade time, handling arbitrary version definition ordering) which I can also look at.

**Comment by dfahlander** [comment]
Indeed, there's an architectural issue with the upgrader function's transaction isntance (see #287). I think one solution to the problem is if Transaction would be subclassed for each Version instance since it currently has getters for each object store as well as the table() method but each Version may have its own set of tables and indexes so a subclassing solution would fix this. The _createTransaction() method should create a new latest Version.Transaction(). Then the provided trans object to the upgrade function should get a correct API instead of just the latest version's API as it is now. The API should include previous version's stores PLUS added stores in current. This would also solve #1.

Another thing that I would like to make possible, is to stop requiring developers to save old version specifications unless they have an attached upgrader to it or it's next version. This would be possible by examining the current state instead of relying on the specified versions only.

**Comment by dfahlander** [comment]
Please let me know if you'll be working on this. I'll try to keep my hands off Dexie for the coming couple of weeks.

**Comment by chrahunt** [comment]
I am working on this. I have a preliminary solution [here](https://github.com/chrahunt/Dexie.js/tree/use-deleted-in-upgrade) that addresses the initial test, but I need to add several more.

**Comment by dfahlander** [comment]
@chrahunt, will you be doing any more work on your pull request?

Kind regards, David

**Comment by chrahunt** [comment]
@dfahlander I will resume working on this soon.

**Comment by dfahlander** [comment]
@chrahunt Ok, that's good news 👍 Much appreciated. If you however would find youself in short of time, that's totally ok - just drop me a comment and I'll take over.

You will need to re-merge from master before resuming the work because a lot has happened in master since your last PR. One changed internal API is setApiOnPlace(). Take a close look its new signature and adjust your code for it.

Some requirements to keep them in mind. You don't need to support them in your PR but if you do, it's just a bonus:

1. Should diff from installed schema rather than from the declared one. This would enable users to skip saving old version declarations in code unless they've attached an upgrade() function to it.
2. If a non-unique index is changed to be unique, the framework should not fail for duplicates keys. Instead, it should remove duplicated records by default. The upgrade() callback should be invoked before changing indexes, so that the user may resolve unique indexes manually before the framework runs the default behavior.
3. Table instances that are created during upgrades (using setApiOnPlace()) should omit any hooks so that mapped classes, CRUD hooks etc are not invoked. This is not documented but should be. Need to change setApiOnPlace() and Table constructor to allow empty hooks if desired (Discussed in #372).
4. In #349, it was requested to have some kind of recreate() support for a specific version - to drop all tables and recreate them empty. Might be useful when you've changed your model totally and just want to start over on a blank sheet.

Other notes:
* Code completion stuff (like fake() etc) are not that important anymore. It only works in Visual Studio when not using modules.
* Try keeping the code as small as possible.
* In #374, it was requested to call non-indexedb async work within an upgrade transaction. You can skip this discussion for now because I'm curious to see if that one could be solved more generally instead supporting [Transaction.waitUntil()](https://github.com/inexorabletash/indexeddb-promises) using @wwoods [busy wait approach](https://github.com/dfahlander/Dexie.js/issues/374#issuecomment-262426569). In a future version of IndexedDB, we could start using the real waitUntil().

**Comment by chrahunt** [comment]
@dfahlander after looking at the code a bit I had a thought. Would it make sense to upgrade step-by-step more explicitly? Closing and reopening the db between each step, e.g.

```js
this.open = function(version = null, max_version = Infinity) {
  let max_specified_version = getMaxVersion();
  return new Promise((resolve, reject) => {
    let req = version ? indexedDB.open(name, version)
                      : indexedDB.open(name);

    req.onupgradeneeded = (e) => {
      let version = e.target.result.version;
      if (!versions[version]) {
        throw new exceptions.InvalidArgument(
          'Version data must be specified.');
      }
      let schema_now = getCurrentSchema();
      let next_schema = versions[version].schema;
      do_upgrade(schema_now, next_schema);
    };

    req.onsuccess = (e) => {
      let db = e.target.result;
      if (db.version < Math.min(max_version, max_specified_version)) {
        let next_version = versions.find(v => db.version < v);
        this.close();
        // async recurse
        resolve(this.open(next_version));
      } else {
        let schema_now = getCurrentSchema();
        removeAllTableApi();
        setTableApi(schema_now);
      }
    };

    req.onerror = (e) => {
      // Catch version error, rethrow unless we have a higher version we can try.
      // to accommodate multiple pages accessing the db at the same time.
    };
  });
};
```

I think it may be able to simplify the code in a few places and allow us to make stronger assumptions on behavior that may not be well-defined now. Notes:

1. Each new version would only need to include the current database schema (which could be derived on inspection from the object stores, as desired) and the Version corresponding to the current database version. Where now we preemptively calculate desired state for each version it could be deferred and done between the current schema and that provided to the version we're currently using.
2. The upgrade of the database would ratchet forward, always getting closer to the desired state. Currently because we're doing everything in a single upgrade transaction we may run into 2 issues:
    1. The maximum resources we may need to execute the transaction grows as a function of both database size and the number of versions we need to upgrade through. This can be mitigated by browsers assuming the underlying implementation prunes unused/removed items. What cannot be mitigated is the possibility of increasing memory consumption at the application level if developers are holding references to objects without realizing it. Maybe this wouldn't be a problem for a single upgrade but several in succession?
    2. The maximum time needed to execute the transaction also grows as a function of the number of versions we need to upgrade through and database size. This is especially relevant as we move to allowing async operations in the context of a transaction. The time needed to upgrade between 2 versions may be well known and tested, but depending on how much control and information developers have, it could be an unknown exactly how many versions need to be upgraded through if some users fall behind.

3. Related to 2.i, if a single upgrade function fails then the database itself is left in a consistent state immediately before the bugged upgrade. If the reason for failure is transient then after a refresh instead of requiring the same amount of time and work to be done, it can pick up where it left off.
4. The workaround for IE proposed in #1 could just be implemented as a special case of the same approach. `ifIEBug()` then check if the next version introduces a deletion of a current object store and if so push an intermediate version into the list and recurse with that set as the next one.
5. Attempted accessed of the database from different instances of the same code will work the same. The database will either be in the middle of an upgrade transaction (blocking the other access) or just closed, in which case our current page will pick it up in the same way.

**Comment by dfahlander** [comment]
It seems you're on to a beautiful solution. I'll read through your text again tomorrow to get a deeper understanding of the details.

**Comment by dfahlander** [comment]
Everything that simplifies the logic without sacrificing correctness is a good thing.  Your approach would not only simplify logic but also possibly spare resources. Testability better as well. 

Wondering though if not the recursion should be on an internal db._open()  or so.  There are tasks executed at end of db.open such as triggering open ready promise and db.on.ready subscribers. Also, Dexie addons may override the public db.open method.

**Comment by chrahunt** [comment]
I agree, an internal method should be used instead and the same for `close`. Are there any implications for add-ons that you can think of? Outwardly for application code I think internal calls to `_open` and `_close` should be transparent, but addons might have need to override/be notified.

**Comment by chrahunt** [comment]
This isn't actually fixed, but was closed by a PR that was eventually reverted.

**Comment by sechel** [comment]
Can we resume working on this? I have a similar problem with the upgrade routine. If I introduce a temporary table to workaround a migration issue I'm having with Firefox, I cannot access via Dexie tables unless I refrain from setting it `null` in subsequent upgrade steps:
```javascript
QUnit.test('Migrate', async assert => {
  db = new Dexie(dbName);
  db.version(1).stores({test: '++id'});
  db.open();
  db.close();
  db = new Dexie(dbName);
  db.version(1).stores({test: '++id'});
  db.version(2).stores({test: '++id', test_tmp: '++id'})
  .upgrade(t => {
    t.db.table('test_tmp').put({id: 1});
  });
  db.version(3).stores({test_tmp: null});
  try {
    const obj = await db.table('test_tmp').get(1);
    assert.deepEqual(obj, {id: 1}, 'successfully migrated');
  } catch (error) {
    assert.notOk(error);
  } finally {
    await db.delete();
  }
});
```
See this Fiddle: https://jsfiddle.net/sechel/aLrg1q6p/
@chrahunt Can you separate the solution from the earlier PR and commit as a new PR?

**Comment by sechel** [comment]
The funny thing is that the object store is really there. I can use the native API and work around this issue myself. But a fix would be great anyway.

**Comment by sim642** [comment]
I'm trying to change a primary key with 3.0.0-alpha.3 like the test suggests: https://github.com/dfahlander/Dexie.js/blob/e956de3b74cf3ac5f1ed2fa2b97b53e4fe60a3e1/test/tests-upgrading.js#L566-L602

That is rather verbose because store deletion happens in separate versions so I tried to shorten it by doing the following instead:
```js
    // To change primary key, let's start by copying the table
    // and then deleting and recreating the original table
    // to copy it back again
    db = new Dexie("changePrimKey");
    db.version(1).stores({
        foos: '++id'
    });

    // Add version 2 that copies the data to foos2
    db.version(2).stores({
        foos: null,
        foos2: 'objId'
    }).upgrade(async tx => {
        const foos = await tx.foos.toArray();
        await tx.foos2.bulkAdd(foos.map(foo => ({
            objId: "obj:"+foo.id,
            hello: foo.name
        })));
    });

    // Add version 3 that recreates "foos" with wanted primary key
    // and do the copying again
    db.version(3).stores({
        foos: 'objId, hello',
        foos2: null
    }).upgrade(async tx => {
        const foos = await tx.foos2.toArray();
        await tx.foos.bulkAdd(foos);
    });
```

This, however, doesn't seem to still work:
```
OpenFailedError: NotFoundError Table foos not part of transaction
```

This comment suggests it should though:
https://github.com/dfahlander/Dexie.js/blob/e956de3b74cf3ac5f1ed2fa2b97b53e4fe60a3e1/src/classes/version/schema-helpers.ts#L73

Is this supposed to work or am I misunderstanding what this issue is about?

**Comment by dfahlander** [comment]
Yes, it's definitely a bit verbose to say the least. Hope to improve it further. But for now, the code you provided won't make it through version 2, as it defines foos to null, and still tries to read from it in the upgrader.

**Comment by dfahlander** [comment]
I see, it may be a bit confusing (and unnecessary verbose) as of now. I'll see what I could do to give access to a to-be-deleted store not only in future version but also current.

**Comment by dfahlander** [comment]
This issue was solved with https://github.com/dfahlander/Dexie.js/commit/827b357a2b3099897364d93b74204684a5df1011
