### ISSUE TITLE
UI freezes on bulkAdd

### ISSUE THREAD

**Issue by Rakantor** [dfahlander/Dexie.js#1058]
Hi there,
I'm working on a Vue.js w/ Vuetify project where I need to locally save a db table containing ~10k rows. I noticed that the UI freezes for a short period of time (1-2s) once the server returns the JSON and bulkAdd() is called.
For testing purposes I ran the example code (100k raindrops) from the docs and that resulted in the UI becoming unresponsive for +10s.
I'm new to IndexedDB and Dexie. Am I doing something wrong or is this behavior expected? If so, what would be the best practices to save large amounts of data to IndexedDB without blocking the UI?

**Comment by dfahlander** [comment]
The best is to let a WebWorker or ServiceWorker to the heavy bulkAdd for you so that the GUI wont freeze. It's also good if the worker can fetch the data to add from server directly instead of your app having to post it to the worker, as the communication between gui thread and workers also could affect GUI performance.

Another good thing is to divide the heavy data into chunks of maybe 200 rows each to not starve the browser's RAM memory.

**Comment by stevebrowndotco** [comment]
I found that staggering the bulkAdd or bulkPut into chunks of 300 records to be very optimal in my experience

**Comment by Rakantor** [comment]
I split the bulkAdd into chunks of 200 rows as advised and the UI doesn't seem to freeze anymore. Maybe I won't even need a Service Worker but I'll see how it goes. Thank you for your help!

**Comment by dfahlander** [comment]
Thanks for sharing :+1:
