### ISSUE TITLE
Make Nested Index in table

### ISSUE THREAD

**Issue by graphicmist** [dfahlander/Dexie.js#1064]
I have a table where schema is like this:
```ts
orders: {
  id: number,
  items: [{
    id: number
  }]
}
```

I want to make indexes to items.*.id . Is it possible directly? I am using table hooks to create custom index for now. Eg. i have created item_ids array index where i store all item ids.  Just want to know if something like items.*.id to index is possible?

**Comment by dfahlander** [comment]
IndexedDB only supports MultiEntry index of plain arrays, not objects in arrays, so your current soltion with table hooks is a good solution to work around this limitation.

You would get better performance though if you would use a middleware instead of a hook (if you are using Dexie 3.x (See https://dexie.org/docs/Dexie/Dexie.use()). In principle you want to override the [DBCore](https://dexie.org/docs/DBCore/DBCore) mutate operation of [DBCoreTable](https://dexie.org/docs/DBCore/DBCoreTable) and check for `req.type === "add" || req.type === "put"` and if so, add the property item_ids based on the items and send further to the downlevel DBCoreTable.

**Comment by graphicmist** [comment]
Using Dixie 2.0 right now. Will look into ver 3.0 and the solution you suggested. Many thanks
