### ISSUE TITLE
How to iterate over all key-value pairs in datastore?

### ISSUE THREAD

**Issue by jagaxa** [dfahlander/Dexie.js#1082]
I'm currently migrating from localForage to Dexie.JS. In localForage, there's a method that iterates over all value/key pairs in datastore. How can I do this in Dexie?

I need access to both key and value but the `.each()` method in Dexie doesn't allow me to that. Alternatively, I can include the key name in the object and call `item.name` but I prefer not to change the structure. Thanks for the help!

LocalForage
```
localforage.iterate((value, key, iterationNumber) => {
    console.log([key, value, iterationNumber])
});
```
DexieJS
```
database.store.each((item, cursor) => {
     console.log([item, cursor])
});
```

**Comment by dfahlander** [comment]
[Collection.each()](https://dexie.org/docs/Collection/Collection.each()) will provide the callback with the IDBCursor, which in its turn contains the key. If you are using [inbound](https://dexie.org/docs/inbound) keys, this is not needed, since you will have the key as a property of the value object, but if you are not using inbound keys, use `cursor.key` to get the key with the value.

```js
database.store.each((item, cursor) => {
     console.log([item, cursor.key])
});
```

**Comment by jagaxa** [comment]
Looks like I need to read the docs more but I appreciate you spelling it out for me. Thank you.
