### ISSUE TITLE
Transaction serialization

### ISSUE THREAD

**Issue by ChicagoSchooler** [dfahlander/Dexie.js#111]
Hi dfahlander,

In my case, a series of other transactions initiated in the middle of another transaction seem to be skipping the original transaction, receiving their results first, causing the performance of the original transaction to suffer.

The original transaction is in a ```window.crypto.subtle.digest``` callback.  All the transactions in question use the ```'rw!'``` parameter.

On the main API Reference page, it says:

> By default, multiple transactions created outside any transaction scope will always launch in parallell

Are there any exceptions to this rule?

**Comment by ChicagoSchooler** [comment]
Whoops.  Please ignore.

```'rw~``` is correct.

**Comment by dfahlander** [comment]
If the original transaction does not perform any operation before the other transactions does, and the other transactions is rw with overlapping tables, it will block the original transaction. If however the original transaction is the first one to perform an operation, the others will wait instead. 

This behavior is because Dexie does not actually start the IndexedDB transaction before any operation takes place. Otherwise the first transaction would be the one to get the lock. 

When I referred to parallelism it can only be parallel if they are readonly, or if they target different tables/object stores.

**Comment by ChicagoSchooler** [comment]
Very interesting.  Thank you.

I'll reopen if I can't resolve it with your clarification.

**Comment by ChicagoSchooler** [comment]
If transactions are being blocked, is the order that they tried to acquire the locks maintained?

Thank you dfahlander.

**Comment by dfahlander** [comment]
Please check what the indexedDB specification says about it.
