### ISSUE TITLE
No more than 42 columns allowed?

### ISSUE THREAD

**Issue by b3wii** [dfahlander/Dexie.js#112]
hi, i need to create a table with 51 columns but i always get 

Uncaught error: AbortError occurred when opening database xxDB

Is there a limit on how many properties an object can have(it works with 42 properties and below but not above 42)?

**Comment by dfahlander** [comment]
Indexed db doesn't have columns since it allows any number of properties to be stored on the objects but you may define indexes bound to some of the properties. There's no limit on the number of indexes to add (what I know of). Check very carefully though, that no index is duplicated in the list of indexes. 

Also, when getting AbortError, this is usually a consequence of an earlier error that wasn't catched. To log all errors, add the following code:

    Dexie.Promise.on('error', function (e) {
        console.error (e);
    });

...and you'll see what actually went wrong

**Comment by b3wii** [comment]
@dfahlander thanx for fast reply

Ok i checked if there are duplicate properties and this is not the case so here is my code:

here i used less than 42 proerties and it works: http://pastebin.com/06xLf6gc

in this case i used 51 properties and it results in "Uncaught error: AbortError occurred when opening database hsmDB": http://pastebin.com/ERAkqfgv

do you have any idea why this happens?

**Comment by dfahlander** [comment]
Have you tried on various browsers/OS? Might be an implementation limitation?

**Comment by b3wii** [comment]
@dfahlander 
I'm using dexie in a windows store app(winjs with newest ie11). It's just weird that using the stores method with a property value string with over 42 comma separated values throws an error but works if there are less than 42...?

**Comment by dfahlander** [comment]
Ok, so I ran your code with Chrome,Firefox and IE11. The result is clear that this is a IE-specific limitation. Should be filed at Microsoft. Thanks for finding.

**Comment by dfahlander** [comment]
Filed at Microsoft: https://connect.microsoft.com/IE/feedbackdetail/view/1464528/indexeddb-createindex-fails-if-more-than-42-indexes#tabs
