### ISSUE TITLE
Promise-agnostic build?

### ISSUE THREAD

**Issue by YurySolovyov** [dfahlander/Dexie.js#116]
Dexie has a build-in Promise implementation, which it uses internally and exposes to an API, but what if I already using a library, like bluebird or just native ES6 Promises?

I think for such build you could assume that there is already a Promises/A+ -compliant library defined, and if not, then it is user's problems.

Of course you should keep current full build for those who just want a simply plug it and start using.

Inspired by [tweet](https://twitter.com/HenrikJoreteg/status/621742214775836672)

**Comment by dfahlander** [comment]
See #20.

**Comment by dfahlander** [comment]
But there's a point to let the lib user decide about this. For example, in Chrome,  idb transactions and Promise cooperate well, so it would be possible to drive from window.Promise. But I still haven't found any other Promise library that works well within idb transactions.

**Comment by YuriSolovyov** [comment]
Did you tried bluebird?

**Comment by dfahlander** [comment]
What I need is a promise library that supports micro tasks and custom scheduling of them. I think this is supported in bluebird but not out of the box. Would need custom integration with bluebird.

**Comment by YuriSolovyov** [comment]
what about[`Promise.setScheduler(Function scheduler) -> void`](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisesetschedulerfunction-scheduler---void) ?

**Comment by dfahlander** [comment]
I would very much like to allow custom Promise when using Dexie but there are a few things that we rely on that cannot be accessed in standard promises, but it would be possible to let Dexie.Promise be subclassed from a custom provided Promise (that uses microtasks and not setTimeout()).

The features Dexie needs from a Promise implementation is:

1. Detect whether the caller catched a rejection or not (catching a rejection shall prevent transaction from aborting, since user handles the error).
2. The Dexie API relies on [Dexie.currentTransaction](https://github.com/dfahlander/Dexie.js/wiki/Dexie.currentTransaction). Need a way to handle [Promise.PSD](https://github.com/dfahlander/Dexie.js/wiki/Promise.PSD)
3. Simulation of sub transactions needs a way to add a tick-finalizer which would be implemented differently depending on promise implementation.
4. Extending the standard Promise is not possible in any browser yet.

So it's not sneezed out of my nose.

It would be very interesting to hear what benefits you would gain if Dexie was able to adapt to a custom promise. Please provide some arguments and it would help me find a solution.

**Comment by YuriSolovyov** [comment]
At the time I was writing this, I strongly wanted to use it with Bluebird, just because it was in my stack, and custom promise implementation seemed like a huge disadvantage and duplication,  it also seemed like with Bluebird we'll get a much better performance, and I was unable to understand that this might not be a code path where we were speding most of our time.

In fact, I wanted not really a promise-agnostic build, but a Bluebird build, just to feel better not worrying about 2 Promise implementations, 

But since it looks like the custom promise implementation is here for the reason, I'm still not hugely happy with it, but I understand things better now and can live with it.
Also, it looks like it still plays nice with any Promises/A+ - compatible implementation, including Bluebird or native promises.

Still, maybe it is possible to get core promise implementation from Bluebird ([with custom builds](https://github.com/petkaantonov/bluebird/tree/2.x#custom-builds), though it is for 2.x, not sure how much relevant it is for 3.x) and extend it where needed, while allowing Bluebird to do all the heavy lifting?

**Comment by dfahlander** [comment]
Thanks for sharing your thoughts and views on this. If Dexie would be able to derive from bluebird Promise, or if we created fork of bluebird with dexie support added, would any of those solutions be good enough?

**Comment by YuriSolovyov** [comment]
I'd just tried to derive from bluebird, and if that fails, just forget it and move on, fork sounds like overkill to me, mainly because of maintenance cost.

**Comment by YurySolovyov** [comment]
I'd closed this since it is no longer relevant
