### ISSUE TITLE
Dexie 3.1 alpha Syntax Suggestion/Question

### ISSUE THREAD

**Issue by cliftonlabrum** [dfahlander/Dexie.js#1182]
I'm trying to convert the example given in the 3.1 alpha announcement to async/await code. In my case, I'm using Vue JS and am trying to just observe when anything in a table changes. I'm wondering how I can shorten the syntax.

Let's start with a shortened version of the example given:
```
import Dexie, { liveQuery } from "dexie";

// Turn any promise-returning function into an observable:
const observable = liveQuery(
  () => getFriendsWithContactInfos({minAge: 18, maxAge: 64})
);

async function getFriendsWithContactInfos() {
  return await db.friends.toArray();
}

const subscription = observable.subscribe({
  next: result => console.log("Got result:", result),
  error: console.error
});
```

I want to be able to end up with something like:
```
//Pass in a query as a parameter; anything changes in "friends"
const observable = await liveQuery(await db.friends);

//Get the results directly when it changes
const results = await observable.subscribe();
```
I want to pass in the observed query in a more concise way (if possible), and then use the results directly from the observer. This is more inline with how I would think it could work and it would make the syntax shorter and simpler to understand (at least for me).

Hopefully that makes sense. 🙂 Let me know if this is possible or any thoughts you have.

**Comment by dfahlander** [comment]
You only need to provide a promise returning function to liveQuery. The example declares it outside just for explanatory puprose. You could equally well declare it inline, but it has to be a function that returns a promise and not just the promise itself, otherwise there wouldn't be a way to re-execute it when needed.

The sample is equivalent to

```js
const observable = liveQuery(() => db.friends.toArray());

observable.subscribe(
  result => console.log("Got result"),
  error => console.error(error)
);

```
Now, the observable you get is an [ES Observable](https://github.com/tc39/proposal-observable) compliant one (like Rx is also) which means subscribe() takes either an object {start, next, error, complete} or three callbacks (onNext, onError, onComplete), subscribe() also returns a subscription so you can unsubscribe from it at any time.

I'm not so skilled on Vue.js to know how to glue this into Vue components, so I invite anyone who is to propose some kind of helper library for that, similary to how 'dexie-react-hooks' makes it usable in ReactJS. I know Vue has its concept of observables as well some how (sligtly different syntax though) and that there are people using Rx observables with Vue, so probably the same utilities they use could be used here too.

**Comment by cliftonlabrum** [comment]
Excellent. Thanks for the explanation!

**Comment by platoscave** [comment]
> Excellent. Thanks for the explanation!

@cliftonlabrum Did you get this to work in Vuejs? Could you provide me with an example?

My `next:` fires just once and retrieves existing rows from indexeddb. When I add a new row, next event does not fire. The record DOES appear under Application->IdexedDB tab in Developer Tools.
 
I'm using : `"dexie": "^3.1.0-alpha.6"`
```
  mounted() {
    this.observeFriends();
  },
  methods: {
    observeFriends() {
      const friendsObservable = liveQuery(
        () => this.$db.friends.toArray()
      );

      friendsObservable.subscribe({
        start: (result) => console.log("Got start:", result),
        next: (result) => console.log("Got result:", result),
        complete: (result) => console.log("Got complete:", result),
        error: (error) => console.error(error),
      });

      setTimeout(() => this.$db.friends.add({ name: "Joe", age: 78 }), 5000);
    }
}
```
Note: I use vue-idb for global access to the $db

**Comment by cliftonlabrum** [comment]
Yes, it worked for me in Vue JS, but I only used the `result` and `error` callbacks, not `next`.

In `main.js`:
```
import Dexie, { liveQuery } from 'dexie'

let db = new Dexie('MyApp')
db.version(1).stores({
  ...
})

Vue.prototype.$db = db
Vue.prototype.$live = liveQuery
```
Note how I create global references to the `db` and `liveQuery` instances. I don't think you need another package for that, but maybe vue-idb does more than that.

Then in the `mounted()` call of a Vue component:
```
let observable = this.$live(() => this.$db.projects.toArray())
observable.subscribe(
  result => this.loadLocalData(),
  error => console.error('Projects subscribe error: '+error)
)
```
And down in my `methods`:
```
async loadLocalData(){
  //Do stuff by querying and refreshing project records
}
```
I hope that helps. 🙂

**Comment by dfahlander** [comment]
Just a note: The "results" callback is actually the "next" callback, just that parameter name happens to be "result". It will be called whenever a change happens that would affect any of the queries you've made along the promise chain of the provided callback. Note also that the contents of that variable is already the result of entire callback so you may use it instead of re-querying the db again.
