### ISSUE TITLE
First operation is slow

### ISSUE THREAD

**Issue by GSGerritsen** [dfahlander/Dexie.js#1185]
I have two operations I run on app startup that look like this:
```
const dbEmpty = await db.isEmpty();
// a few other things
const serverUpdates = await db.updateFromServer();
```
When timing these operations, I noticed that the `isEmpty` check (which just checks if `db.table.count() === 0`) takes ~1700ms to run, and then the second operation is < 100ms. 

However, if I remove the `await db.isEmpty` and just set that to `false`, then suddenly `db.updateFromServer` takes ~1800ms. 

It seems like the first Dexie operation to run is slower for some reason. Is this expected? Is there any kind of manual initialization I need to do earlier in my application to avoid this kind of penalty? I've tried running `db.open` earlier in the application lifecycle to see if this would remove the penalty on the first operation but this didn't make a difference.

Thanks in advance for any assistance!

**Comment by GSGerritsen** [comment]
Closing, turned out to be something obscure but totally unrelated to Dexie!

**Comment by dfahlander** [comment]
Good you found what it was. You were on the right track to call db.open() because that is what happen in background on the first request to dexie - first dexie operation will take a bit longer than others as it will open the database unless having called db.open() in advance, but not as long as the database is already installed this is only about millisecond, not seconds.
