### ISSUE TITLE
RxJS integration

### ISSUE THREAD

**Issue by reusedtire** [dfahlander/Dexie.js#1187]
Hello David,

I am extrememly excited about the latest alpha release of Dexie and have been testing out the live query functionality. Please consider the following situation:

Step 1: Create live query:
const query = liveQuery(() => contactsStartingWithR());

Step 2: "query" is now an Observable which is es-observable compliant.

Question: Is it possible to easily have the observable created from dexie be turned into an RxJS observable, using something such as RxJS "from", or "fromEventPattern" ? I understand that we can currently implement this by creating an RxJS subject that can emit the "next" values from dexie query observable, but it would be a great API feature if we can add methods to the current dexie observable api, such as:

"addEventHandler" and "removeEventHandler" so that we can pass a handler from RxJS "fromEventPattern" to it.

I have linked the "fromEventPattern" docs [here](https://rxjs-dev.firebaseapp.com/api/index/function/fromEventPattern)

Looking forward to your thoughts on this,

Regards
Samrat

**Comment by dfahlander** [comment]
Dear @reusedtire, thanks for bringing this up. The goal is that you should do as follows:

```ts
import { from } from "rxjs";
const rxObservable = from(liveQuery(() => db.todoItems.toArray()));
```

However, it seems we don't provide correct interopability yet with Rx. RxJS tries to follow the [ES observable contract](https://github.com/tc39/proposal-observable#observable) so this should be possible if we'd add this to Dexie's Observable.

Since there's some bug in the operability in Dexie 3.1.0-alpha.4, you'd have to create a function that encapsulates our observable into an RxJS observable:

```js
function dexieToRx<T>(o: Dexie.Observable<T>): Rx.Observable<T> {
  return new Rx.Observable<T>(observer => {
    const subscription = o.subscribe({
      next: value => observer.next(value),
      error: error => observer.error(error),
      complete: () => observer.complete()
    });
    return () => subscription.unsubscribe();
  });
}
```

I will try to fix this in a coming release - or if any Rx-skilled person could try fix this by adding the following code to Observable.ts in Dexie:
```ts
const symbolObservable = typeof Symbol !== 'undefined' && ("observable" in Symbol) ? Symbol.observable : "@@observable";

class Observable<T> {
  ...
  [symbolObservable]() { return this; }
}
```

This will take us one step further, but we still having problems that the subscription does not take place, which would need to be debugged. I suspect we are calling our observer's next handler with incorrect `this`. If so, this would be easily fixed as well.

**Comment by dfahlander** [comment]
A pull-request that fix this would be very welcome! The hints on how to fix it is in the previous comments.

**Comment by digeomel** [comment]
Is this still the recommended way to turn a Dexie observable to an RxJs observable? I can't use `.pipe()` in Angular because the property doesn't exist...

**Comment by RobinKamps** [comment]
How to wrap  Dexie Obersvable in rxjs observable? (so that pipe operator is accessible).
With angular / rx 7.5.7 (need tap, finalize etc.) the operator `from` does not seem to work.

```
import { from } from 'rxjs';

 from(
  liveQuery(() => db.todoItems.toArray())
); 
```

Always getting the error:

```
You provided an invalid object where a stream was expected. You can provide an Observable, Promise, ReadableStream, Array, AsyncIterable, or Iterable.
    at createInvalidObservableTypeError (throwUnobservableError.js:2:12)
    at innerFrom (innerFrom.js:37:43)
    at from (from.js:4:63)
 ````

**Comment by RobinKamps** [comment]
rxjs 6: `from<T>(input: any, scheduler?: SchedulerLike): Observable<T>`

rxjs 7: `from<T>(input: ObservableInput<T>, scheduler?: SchedulerLike): Observable<T>`
