### ISSUE TITLE
Failed to execute 'objectStore' on 'IDBTransaction': The specified object store was not found.

### ISSUE THREAD

**Issue by Winchester37** [dfahlander/Dexie.js#1208]
Hello, where am I doing wrong I would be glad if you could help;

I get an error like this :
<img src="https://i.ibb.co/3ygsHNL/error.png" alt="error" border="0">

But the problem disappears when I take out the getStep function as below.

<img src="https://i.ibb.co/jDcXNLB/basarili.png" alt="basarili" border="0">

<img src="https://i.ibb.co/DM6VthS/getstep.png" alt="getstep" border="0">

**Comment by dfahlander** [comment]
Within the `each()` callback, you're code is executing within a transaction that only has 'options' table in it. When you call getStep(), it won't find the 'step' table in the ongoing transaction.

Solution: Start a transaction in optClick that includes both 'options' and 'step'.

Tip: I would suggest to change the code so that all DB related things are done separate from GUI interactions and communications. Create a function that does the transaction and returns a result to act upon and perform the GUI interactions and call adminSend() / userSend() from outside that DB-facing code. Also avoid `.each()` and use `toArray()` instead which is easier to follow and also more performant as it allows Dexie to use a more optimized way of fetching the data from the db (using IDBIndex.getAll() rather than IDBIndex.openCursor()).

**Comment by Winchester37** [comment]
@dfahlander Thank you so much. I made arrangements according to your suggestions, it works very well. Thank you also for this nice plugin :)
