### ISSUE TITLE
Dexie.Observable excludes tables with names starting with the underscore character from observation

### ISSUE THREAD

**Issue by MisRob** [dfahlander/Dexie.js#1214]
Hello, thank you for all your work on the library and its documentation.

We had decided to use two underscores in the beginning of names of some our tables because we consider them to be more internal than others and want to make a clear distinction. After some time we learned that Dexie.Observable doesn't report updates of tables with names starting with an underscore character:

```
db.on('changes', function (changes) {
    // `changes` array doesn't contain `change` objects for tables
    // with names starting with an underscore character
});
```

The cause of this behavior might be [here](https://github.com/dfahlander/Dexie.js/blob/v2.0.4/addons/Dexie.Observable/src/override-parse-stores-spec.js#L22). I assume that this is happening because Dexie itself uses the underscore character to denote its internal tables. 

We've solved our problem by removing underscores from names of those tables though I wanted to report it because it's possible that it'd been silently causing us some unexpected issues before we discovered it. Maybe it would be good to add a note [to this page](https://dexie.org/docs/Observable/Dexie.Observable)? Or would it be possible to only ignore specific Dexie's tables instead of ignoring all tables starting with an underscore?

**Comment by dfahlander** [comment]
Hi! Thanks for bringing this up. It should be noted into the page as you suggested. If you have a change to edit the page, it will create a PR that I can merge? Otherwise I'll try to do it later.

Depending on your use case, you could also give dexie@3.1.0-alpha a try. It might be a better solution than dexie-observable as it is more performant than the latter and possibly easier to use. The feature is described in [this release note](https://github.com/dfahlander/Dexie.js/releases/tag/v3.1.0-alpha.1) and on [this blog post](https://medium.com/dexie-js/awesome-react-integration-coming-f212c2273d05).

**Comment by MisRob** [comment]
Hi, thank you, I am going to open a PR.
