### ISSUE TITLE
Why do events only propagate locally if the tab is visible?

### ISSUE THREAD

**Issue by johnjesse** [dfahlander/Dexie.js#1251]
https://github.com/dfahlander/Dexie.js/blob/861646b058f4eef8f835eecd34ba2f8472df57fc/src/live-query/propagate-locally.ts#L23

This line seems limiting - If I'm using indexed db to store some application state to trigger a change in one tab - that then affects other tabs ( and that chain might be longer than 2 tabs) then it's possible that I want to hear about the change immediately.

Should the option to queue changes and only apply them when the document becomes visible be configurable?

**Comment by dfahlander** [comment]
No change is being forgotten. Once the tab becomes visible all changes will propagate. If you need to perform non-visible background tasks when a change happens, it's better to use a worker. Also, even if we didn't have this code, it seems browsers will avoid waking up invisible tabs from broadcast events anyway.

**Comment by johnjesse** [comment]
Where is it in the spec that browsers will not pass on broadcast events if the tab is hidden? And if the browser is going to throttle/suppress the event when visibility changes - why does this code even bother doing that?

There are still use-cases for responding to events when a tab/window is hidden - for instance - if I'm managing a multi window app I may need some windows to respond to changes to do things like close themselves.

**Comment by dfahlander** [comment]
I wrote the check before finding out that the browser seemed to throttle the events anyway. I've been thinking of removing the check just because of that it's happening anyway. The reason I put it there was to spare resources on devices where tabs / windows are left open as I couldn't see any reason for notifying inactive tabs/windows. But I could understand you use case of closing a window - in case a browser wouldn't block the event anyway.

If you want to, try remove the check and create PR with it. We could try one of the samples, like [this one](https://github.com/dfahlander/dexie-useLiveQuery-sample/tree/main/) using the changed version. If you open the sample on multiple tabs, add a friend or click birthday in one of the tabs, then switch to the other tabs, you will see the old data in some milliseconds before being updated with the new data. If your PR changes that behaviour, the browser does not block the event. If you see the same behavior, the browser blocks it. Could be tested on different browsers also. It might be that mobile browsers blocks it totally but some desktop browsers sends it through. We could discuss having the code removed or possibly configurable.

**Comment by rfox12** [comment]
+1 for configurable!  I'm also using a multi-tab app and in rare cases I need to signal a flash (or sound) to the user that something interesting happened in this view.

**Comment by johnjesse** [comment]
> If you want to, try remove the check and create PR with it. We could try one of the samples, like [this one](https://github.com/dfahlander/dexie-useLiveQuery-sample/tree/main/) using the changed version. If you open the sample on multiple tabs, add a friend or click birthday in one of the tabs, then switch to the other tabs, you will see the old data in some milliseconds before being updated with the new data. If your PR changes that behaviour, the browser does not block the event. If you see the same behavior, the browser blocks it. Could be tested on different browsers also. It might be that mobile browsers blocks it totally but some desktop browsers sends it through. We could discuss having the code removed or possibly configurable.

I'll take a look sometime in the next week when I've got time and see what happens.

**Comment by dfahlander** [comment]
I have been thinking about this and I would hope that removing the check would be the best solution, and leave it up to the browser to spare resources on inactive tabs depending on device type / available memory etc. If so, we would not need to introduce any configurable parameter but could just remove [the entire code part that handles this specifically for browser windows](https://github.com/dfahlander/Dexie.js/blob/861646b058f4eef8f835eecd34ba2f8472df57fc/src/live-query/propagate-locally.ts#L17-L37). Would be nice to try how this would affect existing samples.

**Comment by dfahlander** [comment]
In latest version (Dexie 3.2.0-rc.1) the check has been removed.
