### ISSUE TITLE
Typescript - DataError: Data provided to an operation does not meet requirements

### ISSUE THREAD

**Issue by alpha-tango-kilo** [dfahlander/Dexie.js#1252]
Hi there, I'm new to Dexie so this is just as likely to be user error as an actual problem, but I'd still appreciate some advice please

I am using Dexie v3.0.3 with Typescript v4.2.2 to write a web extension targetting Firefox (built using Parcel v2.0.0 nightly). In this example, the extension has both the `storage` and `unlimitedStorage` permission

Dexie database class:

```ts
class SiphonDatabase extends Dexie {
    trackerRequests: Dexie.Table<ITrackerRequest>;

    constructor() {
        super("SiphonDatabase");
        this.version(1).stores({
            // Include only indexed columns
            trackerRequests: ", hostname, sessionUUID", // No primary key
        });

        this.trackerRequests = this.table("trackerRequests");
    }
}
export const DATABASE = new SiphonDatabase();
```

The interface 'shape' of the data:

```ts
interface ITrackerRequest {
    readonly sessionUUID: string;
    readonly hostname: string;
    readonly bytesExchanged: number;
}
```

And the minimal example function I'm using to reproduce the error:

```ts
function exampleError() {
    DATABASE.trackerRequests.put({
        sessionUUID: "abc",
        hostname: "abc",
        bytesExchanged: 312
    }).then(() => console.log("It worked"))
    .catch(err => console.error("It didn't work (" + err + ")"));
}
```

`exampleError` is never called before the database is initialised.

Whenever `exampleError` is called, the error I get is as follows:

```
DataError: Data provided to an operation does not meet requirements.
DataError: Data provided to an operation does not meet requirements.
```

What I've tried so far, both resulting in the same error:
* Adding a primary key
* Remove `readonly` from all attributes

Any ideas?

**Comment by dfahlander** [comment]
Oh that error message wasn't very helpful. It comes from the IndexedDB engine in the browser and could be a bit more concrete I think. The problem is that you need to provide the primary key as a second argument to DATABASE.trackerRequests.put() as you are using an [outbound](https://dexie.org/docs/inbound#example-of-outbound-primary-key) primary key.

The reason you didn't get it to work when switching to inbound key could be that you need to provide the key in its corresponding property if so. It could also be because the key cannot be changed once the database has been created - only indexes can. So you need to delete the database before changing primary key. Dexie should complain (your operations should throw) if you change primary key on an existing table.

**Comment by alpha-tango-kilo** [comment]
Thank you for your detailed response & explanation!

I had added a primary key correctly, but I hadn't reset the database, so that explains why it didn't fix it when I tried.

Using the hidden auto-incrementing primary key works great, so shall stick with that, cheers!
