### ISSUE TITLE
Make use of getAll & getAllKeys when available in IDBObjectStore & IDBIndex

### ISSUE THREAD

**Issue by nifgraup** [dfahlander/Dexie.js#127]
The second edition draft of IndexedDB, https://w3c.github.io/IndexedDB/, defines methods that could speed up some toArray(), limit() & keys() queries. Firefox and Chrome have them implemented behind flags.

**Comment by dfahlander** [comment]
Thanks! I've noticed that and will update Dexie in a future version to optimize toArray() and other methods where possible.

Leaving this open until done.

**Comment by nifgraup** [comment]
These function are now generally available, the flag is no longer needed.

**Comment by dfahlander** [comment]
Fixed in [v1.4.0-beta2](https://github.com/dfahlander/Dexie.js/releases/tag/v1.4.0-beta2).

**Comment by dfahlander** [comment]
Collection.toArray () is now shortcuted with IDBObjectStore.getAll() or IDBIndex.getAll() depending on whether primary key or index is used. Also works if having used limit() on the collection since getAll () accepts an optional limit. 

getAllKeys () on the other hand corresponds to primary keys despite its name but can be utilized by calling the new method Collection.primaryKeys().

On both cases, there are situations when this optimization won't be possible:

1. If offset() is used on the collection 
2. If filter () or and () is used 
3. If any Dexie algorithm is used such as equalsIgnoreCase () or anyOf ().
4. If or() is used 
5. If reverse() / desc() is used.

I.e the query must be a simple Key Range query such as between (), above (), below () or equals (). If not, toArray () and primaryKeys () will fallback to a normal cursor based query.
