### ISSUE TITLE
Modification object in updating hook not correct when changing array

### ISSUE THREAD

**Issue by Christilut** [dfahlander/Dexie.js#1270]
See https://jsfiddle.net/ygaprkbe/2/

In the console you will see `{}` but it should be the object in the `update` call.

So far I've only seen this when updating items inside of an array.

Also, most likely a related bug: https://jsfiddle.net/ygaprkbe/3/

The modifications object here is `{ foo.bar: 444 }` which seems similar to this old bug #1195

**Comment by dfahlander** [comment]
Thanks! I see what's wrong here. Arrays of objects compare equal due to getValueOf() only supporting arrays of simple types. The [commit](https://github.com/dfahlander/Dexie.js/commit/7251bb319104264e056c3e43d9240418f270d89e) that fixed #1195 did compare arrays using getValueOf(). Might need to extend getValueOf() to support objects and go nested.
