### ISSUE TITLE
Cannot add CryptoKeys to table with auto-incrementing primary key

### ISSUE THREAD

**Issue by seshrs** [dfahlander/Dexie.js#1280]
## Context & Repro

Here's a minimal repro:

```js
const db = new Dexie("MyDatabase");
db.version(1).stores({
    keys: "++id",
});

// Create a CryptoKey
const someCryptoKey = (
  await window.crypto.subtle.generateKey(
    {
      name: "RSA-OAEP",
      modulusLength: 4096,
      publicExponent: new Uint8Array([1, 0, 1]),
      hash: "SHA-256",
    },
    true,
    ["encrypt", "decrypt"]
  )
).privateKey;
const objToAdd = { key: someCryptKey };

console.log(objToAdd.key instanceof CryptoKey); // true


// Attempt to add it to the table
db.keys.add(objToAdd);

const storedObj = await db.keys.get(1);
console.log(storedObj.key instanceof CryptoKey); // unexpectedly false
```

The above only repro's when using an auto-incrementing primary key and when the keyPath is not provided in `objToAdd`.

It appears that the root cause is in these lines:
https://github.com/dfahlander/Dexie.js/blob/d6fe43eeaf45fa5992c2288a0bd40d7cd05fef17/src/classes/table/table.ts#L283-L288

Which uses a deep-clone: 
https://github.com/dfahlander/Dexie.js/blob/d6fe43eeaf45fa5992c2288a0bd40d7cd05fef17/src/functions/workaround-undefined-primkey.ts#L6

And it looks like the deep-clone algorithm doesn't work with `CryptoKey` objects.

## Potential approaches for fix?

1. Does `workaroundForUndefinedPrimKey()` need to perform a deep clone? 

2. If we *must* perform a deep clone, would adding `CryptoKey` to the list of "intrinsic types" make the cloning algorithm use the original `CryptoKey` object?
https://github.com/dfahlander/Dexie.js/blob/d6fe43eeaf45fa5992c2288a0bd40d7cd05fef17/src/functions/utils.ts#L193-L194

**Comment by dfahlander** [comment]
We should definitely add CryptoKey to the list of intrinsicTypeNames. That would solve the issue. Thanks for finding it!
The workaround is only needed when the obj is a user-defined class with a declared public field for the primary key:

```js
class KeyEntity {
  id;
  key;
  constructor(key) {
    this.key = key;
  }
}
db.keys.add(new KeyEntity(someKey));
```
As Ecmascript has defined it, each declared public field will be put as a property on the object, even those that aren't initialized. For typescript users that transpile to esnext, this becomes a problem because indexeddb auto-increment will not accept an existing prop of value "undefined". It allows non-existing prop - which will make the ID set by indexedDB, and it will accept an existing prop of a valid key that user defines - but never accept `undefined`. The workaround is there to protect users that declare the id class fields of their entities and want to add them to a table.

We could omit this workaround in case `Object.getPrototypeOf(obj) === Object.prototype || Object.getPrototypeOf(obj) == null` - because then the obj cannot be custom a class instance.

The reason for cloning the object is to be non-intrusive and not introduce new side effects from adding an object.

Conclusion:
1. Add 'CryptoKey' to intrinsicTypeNames
2. Maybe optimize away the workaround by omitting it for plain POJO objects (by checking the prototype).

**Comment by dfahlander** [comment]
My initial suggestion was to check whether the object was POJO or not. I've merged your PR now after refining the check to test more explicitely for having the primary key as "own property set to undefined" instead. Adjusted the tests accordingly. Thanks!
