### ISSUE TITLE
Suggestion: check if database exist

### ISSUE THREAD

**Issue by jimmywarting** [dfahlander/Dexie.js#131]
Something along with:

	Dexie.databaseExists = function(name){
		return new Promise(function(resolve, reject){
			var db = indexedDB,
				req;

			try{
				// See if it exist
				req = db.webkitGetDatabaseNames();
				req.onsuccess = function(evt){
					~([].slice.call(evt.target.result)).indexOf(name) ? 
						resolve(true): 
						reject(false);
				}
			} catch (e){
				// Try if it exist
				req = db.open(name);
				req.onsuccess = function () {
					req.result.close();
					resolve(true);
				}
				req.onupgradeneeded = function (evt) {
					evt.target.transaction.abort();
					reject(false);
				}
			}

		})
	}

	Dexie.databaseExists("foo").then(AlreadyTaken, createDatabase)

**Comment by dfahlander** [comment]
Thanks. Could be handy.
Please make a pull request but use `Dexie.dependencies.indexedDB` instead of just indexedDB because we need to be able to replace the indexedDB API at a single place when needed.

Place the static method close to other static methods such as Dexie.delete(),  Dexie.getDatabaseNames(), etc.

Maybe I'd prefer an `if indexedDB.webkitGetDatabaseNames` rather than catching an exception, of performance and debugging experience (as getNativeGetDatabaseNamesFn() does).

**Comment by jimmywarting** [comment]
Quite new Dexie.js. But I can try my best. Will do it tomorrow tho

**Comment by dfahlander** [comment]
Fixed in commit 5229ea5523e69ec98495ce2123fc15346c1b975f
