### ISSUE TITLE
"between" queries using a compound index with more than two keys only use the first two

### ISSUE THREAD

**Issue by toBeOfUse** [dfahlander/Dexie.js#1338]
I'm working on a mapping application and am trying to use Dexie to query a table of points of interest based on the zoom level at which they should appear, their x values, and their y values. However, when I use an index like this: `"[level+x+y]"` to query them with a "between" clause, the points only appear to be filtered by their "level" and "x" attributes - no "y"-based filtering is done. This is in contrast to queries with e. g. the "equals" clause, which filters results how I would expect. 

The documentation page on compound indexes says it can be used with "multiple properties" at the start but in the "How Compound Index Works" it refers to a compound index as "a concatenation of two properties" - am I meant to be able to create and use an index with three properties? In any case, the wording and behavior is somewhat inconsistent and could be cleaned up.

Below is a simplified version of the code I am trying to write that can be used to test the behavior that I describe.

```js
const pointsOfInterest = [{
    x: 100,
    y: 100,
    level: 1
}, {
    x: 100,
    y: 0,
    level: 1
}];

// creating a database to store simple points
const db = new Dexie("PointOfInterestDB");
db.version(1).stores({
    points: "++id,[level+x+y]"
});
// adding the above points if necessary
db.on('populate', () => {
    db.points.bulkAdd(pointsOfInterest);
});

db.open().then(async () => {
    // an "equals" query using the three-part index works and only produces one matching result:
    const equalsQuery = await db.points.where("[level+x+y]").equals([1, 100, 0]).toArray();
    console.log("looking for level 1, x 100, y 0:", ...equalsQuery);
    // result in console:
    // looking for level 1, x 100, y 0: 
    // Object { x: 100, y: 0, level: 1, id: 2 }

    // this query does not work; it is supposed to look for "y" values between -1 and 1, but:
    const betweenQuery = await db.points.where("[level+x+y]").between([0, 99, -1], [3, 101, 1]).toArray();
    console.log("looking for level between 0 and 3, x between 99 and 101, y between -1 and 1:", ...betweenQuery);
    // result in console:
    // looking for level between 0 and 3, x between 99 and 101, y between -1 and 1: 
    // Object { x: 100, y: 0, level: 1, id: 2 }
    // Object { x: 100, y: 100, level: 1, id: 1 }
    // ^ an extra result appears with a y value of 100 (which is not between -1 and 1)
});
```

**Comment by dfahlander** [comment]
Compound indexes can only be used to compare equality of the leading properties. Only the last property can be searched for the between clause. It cannot be used as geospacial indexes. They are pure btree indexes just like composite indexes in SQLServer or Postgres.

Their values are just arrays of values from the corresponding properties. And normal array comparison rules apply. 

The query returns zero results because neither [100, 100, 1] nor [100, 0, 1] is between [0, 99, -1] and [3, 101, 1] - simply because 100 is not between 0 and 3.

**Comment by toBeOfUse** [comment]
If you look at the console output, you will see that neither of the above queries returned zero results; the first returned one, and the second returned two (which is one too many.) In any case, I see now that I changed the order of the object properties between declaring them and indexing them; the schema [level+x+y] does make it possible for the "between" query to return one of them (even though the properties are listed in the order "x, y, level" when the objects are declared;) I apologize if that was confusing. The problem definitely comes down to too many results being returned for "between" queries, not too few.

**Comment by dfahlander** [comment]
Ok, I get it. Can you do a repro on jsfiddle.net or similar?

**Comment by toBeOfUse** [comment]
Sure. Here is a fiddle that runs the script above and outputs to the console and to the page:
https://jsfiddle.net/L25mp9a7/5/

**Comment by dfahlander** [comment]
Ok. Thanks for the nice repro :)

I see, level was listed first in the index - which confused my last answer. Still the same logic apply from my last response. Compound indexes are not geospacial. They are simple arrays built from picked properties.

The query returns both rows simply because:

* **`[1, 100, 100]`** lies between `[0, 99, -1]` and `[3, 101, 1]` (because 1 lies between 0 and 3)
* **`[1, 100, 0]`** lies between `[0, 99, -1]` and `[3, 101, 1]` for the same reason.

This is just how compound / composite / multicolumn B-tree indexes work in several databases. They work this way in [SQLServer ("composite")](https://www.sqlshack.com/impact-of-the-column-order-in-composite-index-sql-server/), [Postgres ("multi-column")](https://devcenter.heroku.com/articles/postgresql-indexes#multi-column-indexes) and [MongoDB ("compound")](https://docs.mongodb.com/manual/core/index-compound/) and IndexedDB.

**Comment by toBeOfUse** [comment]
Ah, I see. I had not heard of geospatial indexes before, but now that I have, I can clearly see the difference between those and normal compound indexes and won't the mistake of conflating them again. Thank you very much for this explanation and this solution; I have stared Dexie and will continue to use it in my projects in the future.
