### ISSUE TITLE
Dexie Cloud asks for OTP on every page reload

### ISSUE THREAD

**Issue by dusty-phillips** [dfahlander/Dexie.js#1349]
I'm guessing this is just a "local storage hasn't been implemented" thing, but it's making it very difficult to test dexie-cloud. Every time I refresh the page (or HMR refreshes the page), I get prompted to enter my e-mail and OTP again. This is happening in both safari and chrome. I am experiencing other issues with things not syncing reliably, but I don't think I can give more info or an accurate repro until the token storage is fixed.

* dexie-cloud-addon@^1.0.0-beta.2
* dexie-react-hooks@^1.0.6
* dexie@^3.2.0-beta.1

**Comment by dfahlander** [comment]
Hi! Sorry for this. The OTP dialogs are still a work in progress. 

It might be a bug with the `requireAuth: true` option. Try if you can use `requireAuth: false` and show a login button that calls `db.cloud.login()`. The initial sync handshake doesn't need to be authorized. To work around the shaky email/OTP prompt in current beta, you could also authenticate a demo user instead of a real email address.

This is how it is done in the [demo app](https://github.com/dfahlander/Dexie.js/tree/master/samples/dexie-cloud-todo-app). There we currently only login a demo user ([pre-imported](https://github.com/dfahlander/Dexie.js/blob/master/samples/dexie-cloud-todo-app/configure-app.sh) from a [JSON file](https://github.com/dfahlander/Dexie.js/blob/master/samples/dexie-cloud-todo-app/src/data/importfile.json)). Once authenticated, the authentication is persistent.

**Comment by dusty-phillips** [comment]
Awesome, I'll try it out later this week!

**Comment by dfahlander** [comment]
The bug of prompting for OTP on each refresh ( when db.cloud.configure({requireAuth: true}) ) is solved in dexie-cloud-addon@1.0.0-beta.4.

**Comment by paulrosen** [comment]
That is happening to me right now. It didn't happen during an earlier test, but I'm not sure what changed except I'm using a different port in my URL. (Yes, I whitelisted that port)

**Comment by paulrosen** [comment]
I see what my problem was - for my initial testing I wanted to start fresh so I was calling `db.delete();`
