### ISSUE TITLE
select from other query

### ISSUE THREAD

**Issue by sannezuidema** [dfahlander/Dexie.js#141]
Hi I'm making a app where i can store stuff. I have labels and articles. I want to select from te labels the articles.
now he shows:

* kitchen
  * spoon
* living room
  * knive
  * table
  * fork
  * chair

but i want:

* kitchen
  * spoon
  * knive
  * fork
* living room
  * table
  * chair

this is my code :

var db = new Dexie("zusa_app");
            db.version(1).stores({
                labels: 'name, status',
		articles: 'name, label_id, status'
            });
            db.open();
			
			function populateSomeData() {
				return db.labels.where('status').anyOf(0).each(function (labels) {
					 log(labels.name);
					 var labelId = labels.name;
 						
						return db.articles.where('label_id').anyOf(labels.name) .each(function (articles) {
							 log(articles.name);
						 });
				 });
        	}
			
			function log(txt, clazz) {
				var li = document.createElement('li');
				li.textContent = txt.toString();
				if (clazz) li.className = clazz;
				document.getElementById('log').appendChild(li);
			}
			 function runSamples() {
				populateSomeData()
					
				.catch(function (e) {
					log(e, "error");
				});
			}

**Comment by dfahlander** [comment]
It seems you return a promise from within 'each()' and assume it will wait for it to finish before iterating the next item, which is not the case. each() will continue iterating the labels in parallell with your request for articles. That's why you recieve the logs in an undefined order.

I'd suggest you use toArray() instead on the labels and then iterate that array and resolve its articels and wait till each article is resolved. (You could also optimize this further by requesting the articles in one go, but that's over course in the first place).

```js
db.labels.where('status').equals(0).toArray().then(function(labels) {
    // For each label, resolve its articles:
    Dexie.Promise.all (labels.map(function (label) {
        return db.articles.where('label_id').anyOf(label.name);
    }).then(function(labelArticles) {
        // Now we have two arrays: labels and labelArticles,
        // The first one contains all label objects and the second
        // one is an array of article arrays. One for each label.
        // This was possible by using Promise.all() in combination with
        // Array.map() where we mapped each label to a Promise that
        // was resolved with an array of articles for each label.
        for (var i=0; i<labels.length; ++i) {
            var label = labels[i],
                articles = labelArticles[i];

            log (label.name + ": " + articles.join(', '));
        }
    });
});
```

**Comment by sannezuidema** [comment]
hi thank you for your help. I have one little error: Uncaught SyntaxError: missing ) after argument list.
it's at the end of the script by:

     }
    });
});

**Comment by dfahlander** [comment]
Ok, missed out an end parentes at the end of Dexie.Promise.all(). Comment updated. Please try again!

**Comment by dfahlander** [comment]
Promises can give some headache because most people aren't used to writing asynchronic code. This will be improved with Ecmascript 6 and Dexie.Yield addon.

So if you'd target a browser with partial ES6 support, such as Chrome, Opera or Firefox. You can include the Dexie.Yield addon, and the above code could be written like this instead:

```js
Dexie.Yield.spawn (function* () {
    // Dexie.Yield.spawn() will execute this function in a Promise engine so you
    // can use "yield" to await a promise instead of 'then'.
    var labels = yield db.labels.where('status').equals(0).toArray();
    // Dexie.Yied.spawn() also supports yielding an array of promises:
    var labelArticles = yield labels.map(l => db.articles.where('label_id').anyOf(l.name));

    for (var i = 0; i < labels.length; ++i) {
        var label = labels[i],
            articles = labelArticles[i];

        log(label.name + ": " + articles.map(function(a) { return a.name; }).join(', '));
    }
});
```

Yield makes the code looks synchronous and hides the asynchronity from the programmer. Even try/catch will work as expected.

If you must target IE/Edge or Safari, you'd have to stick to the old ES5 syntax as described before. However, you could also transpile the code with Babel to support all browsers and still use a yield-based approach.

**Comment by sannezuidema** [comment]
Thank you very much for helping me. I have one little thing. I want my articles in a div i have try many thing but nothing works i have now:
log (label.name +  artikelen.map(function(a){return "<div>" + a.name "</div>";})
