### ISSUE TITLE
function Dexie is undefined using electron

### ISSUE THREAD

**Issue by felipecaputo** [dfahlander/Dexie.js#142]
First of all, congratularions for the great library! 

I'm doing a application using GitHub Electron and, Dexie is undefined in the application, if a add `new Dexie(db, option)`  it does not identify Dexie.

Debugging, inside Dexie definition protected function, if I set `window.Dexie = Dexie` then it works fine.

The project I'm using it is in gitHub also if you want to test

Cheers

**Comment by alantheprice** [comment]
I just had the same issue.  The root cause is that when using electron, you are using commonJS.  Dexie is built to use commonJS natively.  Since you are not using commonJS for the rest of your project, you need to explicitly load Dexie.  

```
if (typeof global !== 'undefined' && typeof module !== 'undefined' && module.exports) {
      // CommonJS
      window.Dexie = require("dexie");
}
```

**Comment by dfahlander** [comment]
It's not meaningful to set window.Dexie = require('dexie'). Electron has built-in CommonJS support also in web pages so just do `var Dexie = require('dexie')` in the modules where you need it.

In Electron, the only thing to keep in mind, is that you must run Dexie targeting code from a browser window or a web worker, not from the main process (because main process is just a DOM-less node process without indexedDB support).

Else than that, you are free to include Dexie using your preferred module system - plain script include works fine, but I would suggest to use the native commonjs support that comes with Electrion and use require('dexie').

Here's an example page that uses Dexie from within a `BrowserWindow` page:

```html
<html>
 <head>
  <script>
    // Import Dexie
    const Dexie = require('dexie');

    //
    // Declare Database
    //
    let db = new Dexie("FriendDatabase");
    db.version(1).stores({ friends: "++id,name,age" });

    //
    // Have Fun
    //
    db.transaction('rw', db.friends, function*() {

        // Make sure we have something in DB:
        if ((yield db.friends.where('name').equals('Josephine').count()) === 0) {
            let id = yield db.friends.add({name: "Josephine", age: 21});
            alert (`Addded friend with id ${id}`);
        }

        // Query:
        let youngFriends = yield db.friends.where("age").below(25).toArray();

        // Show result:
        alert ("My young friends: " + JSON.stringify(youngFriends));

    }).catch(e => {
        alert(e);
    });    
  </script>
 </head>
</html>
```
