### ISSUE TITLE
_changes per table

### ISSUE THREAD

**Issue by nidhipurnapatre** [dfahlander/Dexie.js#144]
Can I configure Dexie.Observable.js to have different "_changes" table for each data table? 
I have around 50 tables which need to be sync with server. It will be more easy if the changes will be stored in different tables. Is it possible through  Dexie.Observable.js? 

Also I want to know whether the _changes table gets clear automatically for the synced changes or we need to clear it manually?

Thanks

**Comment by dfahlander** [comment]
Unfortunately, the _changes table cannot be configured to track per table instead of the entire db.

However, the table will clean up automatically as soon a sync node (remote or other local browser instance)  have been notified with the changes. This is periodically done in background using a query doing the following:

```js
db._syncNodes.orderBy('myRevision').firstKey()
    .then(function (oldestRevision) {
        return db._changes.where('rev').below(oldestRevision).delete();
```
However,  after all local nodes got informed about all changes in initial sync, the query would contain a huge number of changes to delete that would lock the db for minutes when over 50 000 changes,  so it is now executing in time-framed chunks instead to free up the transaction for other requests during cleanup.
