### ISSUE TITLE
The LIKE operator 

### ISSUE THREAD

**Issue by starbassma** [dfahlander/Dexie.js#146]
Hello,
i would like to kow if there is any way to search for a specified pattern in a column (sql like operator) ?

**Comment by starbassma** [comment]
just found on MDN website
Limitation of IndexedDb :
Full text searching. The API does not have an equivalent of the LIKE operator in SQL.
so it will be a good idea to add this feature to dexie.js

**Comment by dfahlander** [comment]
Dexie is designed to embrace optimal use of indexes. The SQL "LIKE" operator will in many cases require a full search and not be able to utilize an index. That's why Dexie provides only efficient compare methods such as startsWith() etc.

However, you can achieve any pattern matching using the filter() method, but it will not utilize any index but instead scan every item in the object store (table). See sample below:

```js
var db = new Dexie("likeTest");
db.version(1).stores({
    friends: "name,age"
});
db.on('populate', function() {
    db.friends.add({name: "Foo Barsson", age: 33});
});
db.open();

db.friends.filter (function (friend) { return /Bar/.test(friend.name); })
    .toArray()
    .then(function(result) {
        alert ("Found " + result.length + " friends containing the word 'Bar' in its name...");
    });
```

**Comment by pgsridhar** [comment]
@dfahlander 
I added limit and it searches only in 5 records.  I want search whole store and return only 5 records. 
How to do?
```db.friends.filter (function (friend) { return /Bar/.test(friend.name); })
    .limit(5)
    .toArray()
    .then(function(result) {
        alert ("Found " + result.length + " friends containing the word 'Bar' in its name...");
    });
```

**Comment by danicarla** [comment]
How to use a variable?
`var var_test = 'Dani';
db.friends.filter (function (friend) { return /var_test/.test(friend.name); })
`

**Comment by AleTid5** [comment]
> How to use a variable? `var var_test = 'Dani'; db.friends.filter (function (friend) { return /var_test/.test(friend.name); }) `

Im not sure if too late, but what I did is:

```ts
db.items.filter(
    ({ name, issuer }) => 
        [name, issuer].some((field) => field.toLowerCase().includes(search.toLowerCase()))
).toArray()
```

**Comment by dfahlander** [comment]
Yes that's ok. The `filter()` method is not the fastest one though since it makes a full table scan and also loads every full object and not just the requested fields. However, this might not be an issue if the data is not too big.

If you ever need optimization of this and would accept a slight compromise in the search matches, give multiEntry index a try in combination with the lunr library:

```ts

//
// Declare a multiEntry indexed property:
//
const db = new Dexie('itemDb');
db.version(1).stores({
  items: 'id, *keywords' // *keywords is a new multiEntry indexed array property we're adding here
});

//
// Use lunr library for word tokenization (from https://github.com/dexie/dexie-cloud-starter/blob/9b4b70625543f3ff96efaf5db7ca8fa8ee927316/src/app/db/fullTextSearch.ts#L1-L18)
//
import lunr from 'lunr';

// Use Lunr's pipeline to tokenize content into keywords
const lunrBuilder = new lunr.Builder()

export function extractLunrKeywords(...textFields: string[]) {
  // Tokenize content
  const tokenizedWords: string[] = []
  lunrBuilder.pipeline.run(lunr.tokenizer(textFields.join(' '))).forEach((token) => {
    tokenizedWords.push(token.toString())
  })

  return tokenizedWords;
}

//
// When adding an item, also add lunr tokens in a separate multiEntry indexed property:
//
function addItem(item) {
  const keywords = extractLunrKeywords(item.name, item.issuer);
  return db.items.add({
    ...item,
    keywords
  }); 
}

//
// When finding an item, use lunr again to tokenize and then search the multiEntry index
// ( a simplified version of the code from https://github.com/dexie/dexie-cloud-starter/blob/9b4b70625543f3ff96efaf5db7ca8fa8ee927316/src/app/db/db.ts#L182-L212 )
//
function findItem(searchText, maxResults = 50) {
  const keywords = extractLunrKeywords(searchText);
  return db.items
    .where('keywords')
    .startsWithAnyOf(keywords)
    .distinct()
    .limit(maxResults)
    .toArray();
}
```
*NOTE: Code is dry-coded! I cannot guarantee it doesn't have syntax errors. For a full working solution, look at the two files in [Dexie Cloud Starter](https://github.com/dexie/dexie-cloud-starter/tree/9b4b70625543f3ff96efaf5db7ca8fa8ee927316/src/app/db) where I got the inspiration from.*

## What we do here

1. We declare a [multiEntry](https://dexie.org/docs/MultiEntry-Index) index on "keywords" property, making the native IndexedDB engine index every word of that property.
2. When we insert an item, we compute the words that are contained in both the properties 'name' and 'issuer'. We use lunr to ignore stop-words and canonicalize different forms of the same word, such as "run" and "running" - becomes just "run". I think Lunr has plugins for non-english rules too but the default engine works ok with non-english languages too in my experience.
3. When we search, we use the native startsWith operator. It's not like 'includes' but it typically fullfills the use case.
4. We always use a limit. In case the DB contains a million items and you search for a single letter, we don't want the app to stall.
