### ISSUE TITLE
Dexie 1.2.0 WhereClause - equals(null), is(Not)Null(), isTrue(), isFalse()

### ISSUE THREAD

**Issue by magnitudoOrg** [dfahlander/Dexie.js#153]
According to the documentation, equals() doesn't support true, false and also null will not be accepted.
https://github.com/dfahlander/Dexie.js/wiki/WhereClause.equals() 
> "Key to compare with. The key MUST be a Number, String, Date or Array instance. Booleans are not accepted as valid keys"

It seems like there is no isNull() etc. avaiable in WhereClause. (Why?) 
Is there a replacement/work-around for this?
Is Table.filter() the way to go? Does it affect the performance to use filter() instead of where/equals ?
(In my case I need to filter all entries with a property===null...)

**Comment by dfahlander** [comment]
It is because IndexedDB wont index anything else than numbers, dates, strings and Arrays of those types. Null, undefined, true and false are never indexed.

I totally agree about the question "why", but that is how idb works. 

It would be possible to do something to emulate the support of indexing those values but it's not trivial.

**Comment by magnitudoOrg** [comment]
Thank you for the background information!
(Table.filter() is working fine here for my case. :)
