### ISSUE TITLE
How to properly paginate docs with sorting?

### ISSUE THREAD

**Issue by agozie** [dfahlander/Dexie.js#169]
I need to return paginated data with sorting. I have this query ```db.test.where('height').above(20).offset(offset).limit(limit).sortBy(sort)```. How can I sort before the ```offset``` and ```limit```? How best can I handle this? The db contains thousands of documents.

**Comment by dfahlander** [comment]
If you need to sort on another property than the index in the where-clause ("height"), then you need to do: toArray() to get the entire result and then sort the array using sort() method on the result. See question in issue #161. If the page is small and the total result is huge, you could benefit from using an index for sorting instead:

```js
db.test.orderBy('sortIndex').and(x => x > 20).offset(offset).limit(limit).toArray()
```

**Comment by agozie** [comment]
Thanks for your prompt response.
Since ```and(x => x > 20)``` runs on the client instead, won't performance take a hit when the table is huge? Is not possible to do ```where('height').above(20)``` before the ```orderBy('sortIndex')``` that will be handled by indexdb?

**Comment by dfahlander** [comment]
If the offset is relatively small, window is small and the criteria is not very much limiting, then number of operations would be low even if the table is huge.

For example when offset is 0 and limit 25, or would be very fast because it can stop at 25. But as offset increase, it would have to filter out a lot of items. But in many guis. The offset is initially zero to view first page result. 

Indexeddb is limited to not use different indexes for querying than spring, but in fact, any other btree db, including SQL DBs suffers from the limitation.  The difference is that those other DBs decide runtime which way is most optimal for you, and it all depends on how much the criteria filters out data in relations to how large the db is, and how large offset and limit numbers are.

**Comment by agozie** [comment]
Thanks for the insight, it makes sense as my GUI has initial offset of 0 and max limit of 100.

**Comment by jayarjo** [comment]
Ouch... so basically we got to retrieve something and only after that filter and order?
