### ISSUE TITLE
Broken dependencies with new release

### ISSUE THREAD

**Issue by jarrodek** [dfahlander/Dexie.js#191]
In latest minor release the path for dist dexie.min.js has changed. That caused further dependencies breakdown in bower.
Generally it's OK to change the paths if really necessary but if you use tools like bower it may break your app without clear reason. And if it's not a major release.

Unfortunately to prevent further breakdowns like this I have to fix version number to current so next releases I'll have to update manually which probably won't be very often.

It's just a suggestion to clearly communicate major changes in the release by supporting release description and proper versioning. Not an issue per se that you can fix now.

**Comment by dfahlander** [comment]
Hi,

I actually announced the change a month ago in #177. The reason behind not updating the major version was because the API is still backward compatible. And by default when using bower install dexie --save, dependencies are marked with "~", wich prohibit auto upgrading to next minor. But I get your point. That's why I I put the request for feedback in #177 out. Not that it's already done, it's probably nothing to do about it.
