### ISSUE TITLE
Updating - cashebusting

### ISSUE THREAD

**Issue by krisak** [dfahlander/Dexie.js#194]
Hi! I am creating smaller website with aprox 500 smaller textonly articles. I thought i could make the site work offline - because the whole database is actualy quite small. 

So i use dixie simply as readonly - clients cant change the database. 

It works suprisingly well the question i have though is what would be the simplest solution to updating articles that clients already have in db? I dont see this happening very often but it might - grammar corrections etc.. Should i provide version nubmer on the backend and then check compare every article on first load of the client or is there some more clever solution? 

Thanks!

**Comment by dfahlander** [comment]
Glad to hear that Dexie works well for you.

You use case is covered by addon dexie-syncable + your own sync-provider and backend. That said, let me first suggest a simpler solution for your case since you only have one-way sync, just a single table with just around 500 articles.

Put a digest on each article in a dedicated column (server-side and client-side). A sync request could let client query the ids and corresponding digests as an array. This would be a quick response with ~500 articles. Put the response in a javascript map of {articleID: digest}. Client compares:

```js
var map; // Retrieve from server {articleId: articleDigest}
var modifiedArticleIds = [];
db.articles.each(article => {
    if (article.digest !== map[article.id])
        modifiedArticleIds.push (article.id);
    delete map[article.id];
}).then(()=> {
        var newArticleIds = Object.keys(map); // Those not deleted.
        return jQuery.ajax({
            url: "yourBackendUrl",
            data: {
                articles: modifiedArticleIds.concat(newArticleIds)
            }
        });
}).then(data => {
        return db.transaction('rw', db.articles, ()=> {
            data.forEach(article => db.articles.put(article));
        });
});
```

A full-blown solution for this is possible through dexie-syncable addon, which I personally use (even though still in alpha development!). It's a framework for two-way sync but you need to provide your own sync-provider plugin as well as a backend, and the backend need to be capable of tracking all inserts, updates and deletes revisioned by a revision number. I personally have a dedicated "changes" table at the server where I track all changes. When a client connects, it sends its revision and server queries all changes since that revision and responds back to the client.

There's a sample on how to implement a sync protocol and the server side part at https://github.com/dfahlander/Dexie.js/tree/master/samples/remote-sync/websocket. The server side is implemented as in-memory database. You must convert the code to talk with your real DB.

**Comment by krisak** [comment]
Thank you very much for your help!
You are very kind.

I knew about the syncable - i also knew about pouchdb and its way of syncing but i thought for this purpose it will be better someting simpler someting going one way. I never realy realized that the sync is useful not only for comunicaiton client->server but also for updating.
 
I will try to implement your proposed solution tomorrow.
Again thanks for your time.
