### ISSUE TITLE
Safari bulkadd

### ISSUE THREAD

**Issue by JeffB1** [dfahlander/Dexie.js#229]
I know Safari is problematic with IndexedDB but does anyone know if the bulkadd command should work ok?

I've got some code like this:

```
try {
                console.log('Content='+content);
                let data = JSON.parse(content);
                console.log('Add items');
                return pos.items.bulkAdd(data);
            }
            catch (ex) {
                console.log('LoadItemData Error' + ex);
                throw ex;
            }
```
The last message I get is Add Items so it parsed the data and attempted to run bulkAdd. This code works on Chrome and IE but not on Safari. It doesn't throw the catch in this code nor is a catch on the promise thrown. It just hangs. It almost appears that the promise from bulkAdd is never resolved. There are about 250 records it's adding. There will be a log more though once it goes live.

It may not be dexie code but given the issues with Safari I just wanted to know that bulkadd should work before I go down yet another rabbit hole :-)

**Comment by dfahlander** [comment]
Thanks for reporting. The bulk methods are special bec

**Comment by JeffB1** [comment]
I emailed you a copy of the data I am using.

**Comment by JeffB1** [comment]
Hi David

Attached is the json data I am trying to load.

It gets past the JSON.parse(data) and fails on the bulkadd.

Cheers

Jeff

**Comment by dfahlander** [comment]
Thanks! I'll try looking in to it soon. Hopefully next week.

**Comment by alexey-sh** [comment]
@dfahlander how it's going?

**Comment by dfahlander** [comment]
Sorry for stalling on this one. So many IndexedDB bugs has been corrected lately in webkit so I suppose also this one is in the latest technology preview. Need to be verified though. Not sure about if we should have a workaround strategy or not until safari 10 is out. This issue is not the only one for safari.

**Comment by dfahlander** [comment]
@JeffB1 Trying to give your test a go (a little late though...). However, the json data was pasted into the email message and cut off after 64kb. If you still got the data, could you email it as an attachement? Otherwise, I'll try with the first 64kb (which is 100 records) and see if it will reproduce the error on Safari 9 and if it's solved or not in Safari 10.

**Comment by JeffB1** [comment]
Oh wow. I have no idea whether I'd even have that data anymore. It was a while ago I was working on this. I have upgraded OSX and it seems to be working ok now. I'm quite happy with how it's performing.

**Comment by dfahlander** [comment]
Ok. Nice to hear you've got it working after an upgrade. Safari 10 has fixed many indexedDB bugs and our unit tests for bulkAdd works great in Safari10. I'll close this issue.
