### ISSUE TITLE
Dexie.js not working with Chrome Extension

### ISSUE THREAD

**Issue by sujprogrammer** [dfahlander/Dexie.js#233]
I tried to use Dexie.js to store extension data in IndexedDB but it didn't work.
Also, i need to ask one thing.. Can we use dexie.js to store extension data as permanent storage as like lastpass so that data could not be visible from chrome console?

**Comment by dfahlander** [comment]
I know there are others using Dexie in Chrome extensions (#179). I'm not experienced with chrome extensions so maybe someone else could answer?

**Comment by Pandiora** [comment]
It definitely works. I'm using Dexie in background and content-scripts and in a webworker w/o problems. Maybe @sujprogrammer has to provide more information and some of his code.

**Comment by bl0b** [comment]
I too have an issue : I open the same database (name) in a content script and the extension popup, and the contents are different. They seem to each live in their own world.
If I open the same database name in the background script, it has the same contents as the popup. I hope there is a way to make it work simply without resorting to messaging between the content and background scripts to query and update data. :(

**Comment by bl0b** [comment]
Well after some more reading I realize message passing is the only option. I'm a bit sad.

**Comment by dfahlander** [comment]
Closing

**Comment by ravaan** [comment]
Can someone point oto some code examples for dexie in background and content js scripts

**Comment by Pandiora** [comment]
Stop necro'ing a 7 year old issue, the repo owner already got a ton of open issues and not needing you to bump him for not being able to read the documents or look at other projects on Github which utilize Dexie.

**Comment by ravaan** [comment]
Fair point, I apologies

**Comment by Pandiora** [comment]
I'm not up-to-date, so I can't help you much, but since there should always be a background.js - you normally set up a message listener there and ONLY there - at least I remember it that way. ([Example](https://github.com/Pandiora/SteamAccountRoboticAssistant/blob/master/js/background.js)) I'm using "browser" sind I was using a polyfill library, normally it should be "chrome".

Additionally I utilized the webworker-feature for better performance and wrapped some Dexie functions in my own class. ([Example](https://github.com/Pandiora/SteamAccountRoboticAssistant/blob/master/js/database.js))

On the content scripts (which are injected into a website) I can't really access Dexie (since it lives inside my extension) so I have to utilize sendMessage and the background page has to hand over the data to Dexie. ([Example](https://github.com/Pandiora/SteamAccountRoboticAssistant/blob/master/js/contentscripts/autoDiscoveryQueue.js))

But beware, I haven't altered this extension for a long time, I don't even know if it is working anymore. I only believe most of the concepts and principles should still apply, but giving you are crash course about how to develop a (chrome) extension is out of scope here. Good luck.

PS: the manifest.json is key, since you are defining your background-script / etc. there.

**Comment by Muhammadhamd** [comment]
> It definitely works. I'm using Dexie in background and content-scripts and in a webworker w/o problems. Maybe [@sujprogrammer](https://github.com/sujprogrammer) has to provide more information and some of his code.

Could you please show me an example of your code on how you implemented Dexie.js in your extension's file background.js
