### ISSUE TITLE
help structuring schema for searching nested collection

### ISSUE THREAD

**Issue by loriensleafs** [dfahlander/Dexie.js#244]
Hey,

I just came across Dexie and it's pretty fantastic.  I wondered if I could ask you about how to set up a schema for something that feels potentially less complicated then I'm making it.  

Lets say I'm making a app with offline support for files that have been uploaded.  Each file has lets say 20,000 rows, each row matching a set of key/value pairings itself.  The file also has some summary values, id, hasErrors,totalErrors,uploadStatus....etc.

Initially I had done something like this:
```
app.dbs.filesDB.version(1).stores({
	files: '++id, uploadType, contentHash, *rowTemplates, *rows, hasErrors, totalErrorRows, totolErrorFields'
});
```
This feels wrong though because the 'rows' field is a array of 20,000 row objects (same data structure for each row).  I began wondering if it would be better to have a separate object store, or even DB for the rows as I'd like them to also be indexed for filtering/sorting/searching.

Any how, I'm a little new to indexedDB as well as Dexie and was wondering if you had any suggestions for something a little more complicated like this.

**Comment by dfahlander** [comment]
I'd suggest you do it using a relational model of two reasons: 

1. MultiEntry indexes (*) only supports arrays of simple indexable types.
2. With lots of rows, you end up getting a large file object in case you only want to view a list of the files and it's properties to present to user, you wouldn't want to retrieve entire file content each time.

It's very easy. You should add a table for fileRows where you index a 'file_id' property. You can then reterieve all rows of a file using `db.fileRows.where('file_id').equals (file_id).toArray ()`. Primary key could be either auto-incremented, or maybe composite with [file_id+line_no] of you easily want to be able to lookup a file line or a range of lines ( `db.fileRows.where ('[file_id+line_no]').between ([file_id, 100], [file_id, 200])`). Beware though, that composite keys don't work on ie, Edge of safari, so if you want something that works there as well, you could instead use a string where you manually concat file_id + ':' + line_no (sure line_no is padded with zeroes so you can do proper range queries).

Sharing the same database is a good thing since the tables have a relationship and you can protect it with a common transaction.

**Comment by loriensleafs** [comment]
@dfahlander thanks so much for getting back to me so quickly, you've done a pretty amazing job creating a community around Dexie.

I like the relational IDs suggestion.  Question.  If there were multiple files in the files table, there would then be rows belonging to different files in the rows table.  As this table gets to be quite large would making queries to get a specific table's rows become really slow, or does indexedDB optimize for this?

If you made a collection of the table's rows with Dexie, does this optimize future queries into that collection, or is it really just for caching the query definition?

**Comment by dfahlander** [comment]
Thanks :) You can be certain that every access to the fileRows table will be super fast no matter database size. Reason for this is that if you use a primary key (or index) consisting of both file_id and a line number (typically a composite index but equally fast with using a concatenated string of file_id + ':' (line_number padded with zeroes). Even though fileRows table contains rows from various files, their indexing strategi ensures fast lookup when knowing the file_id in advance. This is how all SQL based databases work.

For example, if querying the lines from 100 to 199 of file X using the query:

```js
db.fileRows.where('[file_id+line_no]').between([file_id, 100], [file_id, 200]).toArray();
```
This will translate to a simple range query with indexedDB.

If you want to retrieve the whole file including the fileRows for that file, you could do something like:

```js

var db = new Dexie('dbname');
db.version(X).stores({
    files: '++id, ...',
    fileRows: '[file_id+line_no], file_id'
});

function getFileWithRowsIncluded(file_id) {
    return Dexie.Promise.all([
        db.files.get(file_id),
        db.fileRows.where('file_id').equals(file_id).toArray()
    ]);
}
```

And to use that function:
```js
getFileWithRowsIncluded(file_id).then(function (fileAndRows) {
    var file = fileAndRows[0],
        rows = fileAndRows[1];
});
```
You could actually omit the 'file_id' index and only use the primary key to get but instad of equals(file_id) you would use `where(':id').between([file_id, 0], [file_id, Infinity])`.


Your last question: No, a Collection does not optimize for further requests towards it but is just a preparation for how to do the query when calling toArray() or each().

**Comment by dfahlander** [comment]
Closing
