### ISSUE TITLE
How to use the update query?

### ISSUE THREAD

**Issue by Script47** [dfahlander/Dexie.js#247]
@dfahlander I've made a store which doesn't have any primary keys as I wish to update all the fields. I'm struggling with the usage of update query, namely the first parameter in the update query function, on [this](https://github.com/dfahlander/Dexie.js/wiki/WriteableTable.update()) page it says key (the first parameter) refers to a primary key but as I mentioned I don't have a primary key. So, how would I go about using this query?

The code below is what I have, as you can see I'm missing the first parameter because I don't have a primary key.

```javascript

db.User.update(obj).then(function (isSuccessful) {
    if (isSuccessful)
        return self.refresh();
});

**Comment by dfahlander** [comment]
How is your schema defined? There will always be a primary key but it can be [inbound or non-inbound](https://github.com/dfahlander/Dexie.js/wiki/inbound).

**Comment by Script47** [comment]
@dfahlander

```javascript
$scope.db.version(1).stores(
    {
        User: 'name,current_experience,total_experience'
    }
);

**Comment by dfahlander** [comment]
Add your schema is defined, you use name as primary key. If that's not what you want, use a dedicated id, or if you don't want an inbound primary key, let the store-specification begin with a comma. If so (not inbound) you must always provide the primary key as a second argument when calling add or put. Still of you want to use the update method rather than the similar put method, you will still have to provide the primary key of the item to update.

**Comment by Script47** [comment]
@dfahlander thanks for the quick support, got it working. Awesome library, excellent work. :+1:

**Comment by dfahlander** [comment]
Nice you solve it.
