### ISSUE TITLE
How to create a table based on the variable table name?

### ISSUE THREAD

**Issue by shunok** [dfahlander/Dexie.js#259]
I need create a lot of data tables, more then ten thousand, How to create a table based on the variable table name?

Thanks very much!

```
function createTabel(dbName,ver,tablePosition,range){
    if(!dbName || !ver || !tablePosition || !range) return false;
    var tableName = getTableName(tablePosition,range);
    if(!tableName) return false;
    Dexie.exists(dbName).then(function(exists){
        if(exists){
            var _db = new Dexie(dbName);
            if(_db.isOpen()) _db.close();
            _db.version(ver).stores({
                [tableName]:"id,value"
            });
            _db.table(tableName).add({id:1,value:"12345"});
            _db.open();

        }else{
            var _db = new Dexie(dbName);
            _db.open();
        }
    }).catch(function (err) {
        console.log(err);
    });
}
```

**Comment by dfahlander** [comment]
First of all, you don't need to use `Dexie.exists()`. Just do `db.open()` and it will create the database if it doesnt exist, upgrade it if nescessary, and otherwise just open it.

Secondly, I am very curious about why you would create ten thousands of tables. A table (or ObjectStore) generally represents a class, not an instance. Some use cases solved with multiple tables per object can generally be solved using a compound primary key instead. I am not sure that the implementations indexedDB will accept ten thousands of objectStores either, but you could always test. 

That said, I will try to answer your question. Let's assume you have all your table names in an array, tableNames. Then you need to convert that array to a javascript object where each key is the name and each value its schema.

```js
var stores = {};
tableNames.forEach(function (tableName) {
    stores[tablename] = schema; // where schema is a string containing the primary key name + "," + a comma-delimited list of indexes.
});
db.version(x).stores(stores);
db.open(); // Here's where the tables are created if db is not installed or if upgrade is needed.
```

**Comment by shunok** [comment]
Dexie is a wondeful kit. thanks.
