### ISSUE TITLE
problem with iOS safari and chrome

### ISSUE THREAD

**Issue by michael2043** [dfahlander/Dexie.js#272]
working with code below:

db = new Dexie("idb01");
 db.version(1).stores({ tbl03: "[id1+id2],name,age" });
db.open();

db.transaction('rw',db.tbl03,function(){
		db.tbl03.add({id1:"01",id2:"01",name:"aaa",age:11});
		db.tbl03.add({id1:"01",id2:"02",name:"bbb",age:22});
		db.tbl03.add({id1:"02",id2:"01",name:"sss",age:55});
		db.tbl03.add({id1:"03",id2:"01",name:"ddd",age:44});
		db.tbl03.add({id1:"03",id2:"02",name:"ddd",age:33});
});

when I debug it with MacBook Safari,data is very strange,see the blew(I can't upload the image....)

key-id1,id2           value
Array(2)                  Object
0 "01"
1 "01"

Array(4)                Object
0 "01"
1 "01"
2 "01"
3 "02"

Array(6)                Object
0"01"
1"01"
2"01"
3"02"
4"02"
5"01"

Array(8)                Object
0"01"
1"01"
2"01"
3"02"
4"02"
5"01"
6"03"
7"01"
.........

**Comment by dfahlander** [comment]
Some questions:
1. What do you mean by Array(2) Object etc..? Is it from a query you've done? If so, could you provide the query as well? Or is it from a DB inspector tool of some kind?
2. Could you point out one of the Array(X) Object where you see an issue and what you would have expected instead?

**Comment by dfahlander** [comment]
Generally though, chrome on iOS run Safari underhood, so if there is a Safari issue, you will see it in Chrome as well ;( .

Safari's indexedDB support has been broken since its first release. Now it has started improving but they're not yet quite there (even though it seems they are getting there very soon). Until then, you might consider using [IndexedDBShim](https://github.com/axemclion/IndexedDBShim) if you're on iOS - it will use WebSQL as backend instead of indexedDB.

```html
<script>
if (is_on_ios) {
    document.write('<script src="indexeddbshim.js">\x3C/script>');
}
</script>
```

[IndexedDBShim](https://github.com/axemclion/IndexedDBShim) is not perfect either. But with current state of the Safari indexedDB, it's better.

The latest technical preview of safari browser has fixed a lots of issues with indexedDB support, but still has [one quite severe issue](https://bugs.webkit.org/show_bug.cgi?id=158833). But given the speed they've been fixing issues so far this year, I'm hopeful we will see a decent indexedDB support in safari quite soon.

**Comment by michael2043** [comment]
sorry for some reason I upload the image by using MacBook Chrome

>1. What do you mean by Array(2) Object etc..? Is it from a query you've done? If so, could you provide >the query as well? Or is it from a DB inspector tool of some kind?
I use Safari on MacBook to inspect into Safari on iPad,after db.tbl03.add(.....) and refresh the page I see data in tbl03 is like that....(**iOS8**)

>2. Could you point out one of the Array(X) Object where you see an issue and what you would have >expected instead?
data in Object is OK

this morning I test it on iOS9 and I saw the data is OK ,but a new problem is when I use where to query,the result is not correct

db.version(1).stores({ tbl09: "MENU_ID1,MENU_NAME,MENU_TYPE" });
db.tbl09.clear();
db.transaction('rw',db.tbl09,function(){
		db.tbl09.add({MENU_ID1:"01",MENU_NAME:"01",MENU_TYPE:"aaa",DEL_FLG:"0"});
		db.tbl09.add({MENU_ID1:"02",MENU_NAME:"01",MENU_TYPE:"BBB",DEL_FLG:"0"});
		db.tbl09.add({MENU_ID1:"03",MENU_NAME:"02",MENU_TYPE:"aaa",DEL_FLG:"1"});
		db.tbl09.add({MENU_ID1:"04",MENU_NAME:"02",MENU_TYPE:"CCC",DEL_FLG:"1"});
		db.tbl09.add({MENU_ID1:"05",MENU_NAME:"01",MENU_TYPE:"aaa",DEL_FLG:"0"});
});

db.tbl09.where("DEL_FLG").equals("0").toArray(function(list){
	console.log(">>>>>>"+list); // 0    (???? why ???)
});

db.tbl09.where("DEL_FLG").equals("1").toArray(function(list){
	console.log(">>>>>>"+list); // 0    (???? why ???)
});

db.tbl09.where("MENU_TYPE").equals("aaa").toArray(function(list){
	console.log(">>>>>>"+list); // 3
});
