### ISSUE TITLE
Index all nested properties

### ISSUE THREAD

**Issue by anrw** [dfahlander/Dexie.js#278]
Hey all,

Currently, to index nested properties you need to define them like this:
`db.version(1).stores({tasks: "&id, name, date.day"});`

This works just fine, however is there a way to add all child indexes at once, like `date.*`? In my example, the date property has many key-values and in different situations all of them are in use.

Also, thank you for such a cool library!
Andrew

**Comment by dfahlander** [comment]
No, each index need to be explicitely defined.

**Comment by anrw** [comment]
Thank you @dfahlander, anyway I think it will be a good feature to have.

**Comment by dfahlander** [comment]
Yes it would've been nice, but indexedDB works similar to an sql system were indexes are statically defined. Having a wildcard based keyPath would require the physical indexes to be created dynamically at runtime. This is impractical with indexedDB because it would require all db connections to close before increasing version number and adding a new index, then reopen the db.

**Comment by dfahlander** [comment]
If you get long lines in the stores spec, you can always do:

```js
db.version (x).stores({
    tasks: [
        'id',
        'name',
        'date.day',
        'date.year',
       ... 
    ].join(',');
});

```

**Comment by anrw** [comment]
That makes sense, thank you for detailed response.
