### ISSUE TITLE
How can i use dexie in my angular app i.e - in my Controllers ?

### ISSUE THREAD

**Issue by mbj36** [dfahlander/Dexie.js#301]
I want to use bower and require js for consuming dexie. I want to use dexie inside my controllers without using it wrapper library ngDexie. How can i do it ?

**Comment by acicali** [comment]
This doesn't really pertain to Dexie, but more to Angular in general. You *could* just reference Dexie from within your Angular controllers. JavaScript will climb up the scope chain and look for the Dexie that you're referencing, eventually finding it at window.Dexie (because it exists in the global scope).

That method goes against Angular's dependency injection though. A better way might be to declare window.Dexie as a constant in Angular, then you can inject it into your controllers.

Something like this:
`
angular.module('myApp').constant('dexie', window.Dexie);

// then in your controller
angular.module('myApp').controller('myController', function($scope, dexie){
    // use dexie as described in Dexie's documentation
});
`

That said, like any other interaction with an API or data store in Angular, this functionality really belongs in a **service**. I recommend using the method above, but injecting Dexie into a **service** where you do your data work. Then inject the service into your controller and use it.
