### ISSUE TITLE
TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in strict mode

### ISSUE THREAD

**Issue by JoepCre** [dfahlander/Dexie.js#365]
I use dexie.js ( latest version 1.5.1 ) in a Cordova based iOS application.
For me this works great. Except in the following scenario:

In my index.html I have a function onDeviceReady when Cordova is ready.
In this function I defined a fetchCallback function which should read my indexeddb via Dexie.

I get the following error message "TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in strict mode" on code line: 		 db.routeItems.where("Id").equals(sId).and(function(item) {
						return item.Statusbezoek === "OPEN";
		 }).count().then(function(iCount) {
						console.log(iCount);
		 });

To prove that in this state of the application I can read from my indexeddb, I made use of the native indexeddb statements:

var db;
var request = indexedDB.open("Chauffeur");
  request.onerror = function(event) {
      alert("Why didn't you allow my web app to use IndexedDB?!");
  };
  request.onsuccess = function(event) {
      db = event.target.result;
      db.transaction("routeHeader").objectStore("routeHeader").get("0010000092").onsuccess = function(event) {
          console.log(event.target.result.Regio);
      };
  };

This will give me a correct result.

Full code:

        function onDeviceReady() {
        	
        	    // Now safe to use device APIs
                var Fetcher = window.BackgroundFetch;
                
                // Your background-fetch handler.
                var fetchCallback = function() {
        	
                    console.log('[js] BackgroundFetch initiated');
                    
                    var db = new Dexie('Chauffeur');
                    
                    db.version(1).stores({
                                            routeHeader: 'Id,Statusdagroute',
                                            routeItems: '[Id+Itemid],Id,Itemid',
                                            routeLading: '[Id+Ladingitemid],Id,Vaccinsoortid,Artikelid',
                                            routeItemsArtikelen: '[Id+Itemid+Leveringitemid],Id',
                                             routeItemsSync: '[Id+Itemid],Id,Itemid'
                                        });
                                                     
                    console.log(db);
                                                     
                    var sId = "0010000093";

		 db.routeItems.where("Id").equals(sId).and(function(item) {
						return item.Statusbezoek === "OPEN";
		 }).count().then(function(iCount) {
						console.log(iCount);
		 });
                }

**Comment by dfahlander** [comment]
That's strange because Dexie does not use neither `arguments.callee` nor `Function.prototype.caller`.

The error message (as you citated it), sais that `arguments` cannot be used in strict mode, but that is not true.

Think you need to find out exactly where this error is thrown by using a debugger with "break on caught exception" checked. Make sure to use non-minified sources as well.

**Comment by dfahlander** [comment]
Though, when Dexie.debug = true (which is the default when accessing your app from localhost), Dexie will intentionally access a function.argument to trigger this exception to store the stack. This only happens on IE browser because it will need a thrown exception in order to retrieve a stack. Happens in debug.js in `function getErrorWithStack()`.
