### ISSUE TITLE
Slow execution of delete operations

### ISSUE THREAD

**Issue by FooSoft** [dfahlander/Dexie.js#367]
Greetings,

I'm using Dexie.js for working with a pretty large database (around 600,000 rows at present), and while most operations (including import) are reasonably fast, deleting rows is painfully slow (maybe around 80 rows per second). So basically a table I can populate in 10-15 seconds takes like 10 minutes to selectively delete from. Is there something silly about the way I'm doing things, or is deletion just always going to be slow?

Database initialization:

```
    init() {
        if (this.db !== null) {
            return Promise.reject('database already initialized');
        }

        this.db = new Dexie('dict');
        this.db.version(1).stores({
            terms: '++id, dictionary, expression, reading',
            kanji: '++, dictionary, character',
            entities: '++, dictionary',
            dictionaries: '++, title, version',
            meta: 'name, value',
        });
    }
```

Code to delete data:

```
    deleteDictionary(title) {
        if (this.db === null) {
            return Promise.reject('database not initialized');
        }

        return this.db.terms.where('dictionary').equals(title).delete().then(() => {
            return this.db.kanji.where('dictionary').equals(title).delete();
        }).then(() => {
            return this.db.entities.where('dictionary').equals(title).delete();
        }).then(() => {
            return this.db.dictionaries.where('title').equals(title).delete();
        });
    }
```

I've tried breaking up the delete operations, using `bulkDelete`, but nothing seems to help in getting performance to be acceptable in my extension. Any advice would be much appreciated. 

*edit: I'm running the Dexie beta, but I had same issue on 1.5*

**Comment by dfahlander** [comment]
That was an issue before (#208) but a lot of effort has been done to solve #208. Delete operations have  been optimized as close to maximum as possible using different approaches for different browsers (avoiding certain bugs in IE and edge). However the speed may vary between browsers. But 100 rows a second seems like it used to behave before the fix.

What browser engine are you using and which version? What version of Dexie are you using?

**Comment by dfahlander** [comment]
Are you using a transaction?

**Comment by FooSoft** [comment]
Thank you for the quick response! My code is running on `Chrome Version 54.0.2840.90 (64-bit)` on Linux Mint. I am using the `Dexie 2.0.0-beta` release (the one linked on the GitHub page). I don't know if it makes any difference, but this is a browser extension.

I am not using a transaction, and am trying to just get the rows dropped by any means possible. 

Please let me know if there is anything I can do to help you investigate this issue.

**Comment by dfahlander** [comment]
I think it's becaused you are deleting the items one by one which results in that IndexedDB needs to reoptimize its internal structure because every other operation is a a query while the previous was  delete operation. You're also awaiting one transaction commit for each deletion which is also slow.

You could do it all in one parallell query. See if it helps:

```js

    deleteDictionalries (titles) {
        return db.transaction('rw', this.db.terms, this.db.kanji, ..., ()=>{
            return Promise.all([
                this.db.terms.where('dictionary').anyOf(titles).delete(),
                this.db.kanji.where('dictionary').anyOf(titles).delete(),
                ...
            ]);
        });
    }
```
If the query is deleting hundreds of thousands of entries, this may take time anyway. In that case, you could use a `limit(1000)` and show some progress while doing the massive delete, then rerun it until the delete operation completes with zero deletions.

**Comment by dfahlander** [comment]
I see. Of some reason, delete seems to be slower than inserts. Manipulations are much slower than reads. Queries should be fast if using indexes to query even with large data.

Seems that you've stumbled on a bug in chrome similar to the one described in #208 that made Edge corrupt its indexedDB. Dexie has a built-in protection from that bug for ie/edge but not for chrome. But you can avoid it by adding a limit() to the delete query.

IndexedDB has a delete method where you can pass an IDBKeyRange as argument instead of just a single key. Deletes normally becomes up to 5 times faster when doing so. But probably this should be avoided also with chrome if the IDBKeyRange resolves to a huge number of records to avoid this bug. If you pass a limit to the delete query, Dexie cannot use an IDBKeyRange but has to delete items one by one instead. But it does it by first querying items to delete, then bulkDeletes them, so it's still OK in performance. 

Let me know if you can use the limit ()  approach and at what speed it deletes your records.

I would actually advice you NOT to use this loop in a transaction if it takes time. It would starve other requests. Test if a limit of 1000 is good enough and log or show some progress before rerunning the 'limited' delete query.

**Comment by FooSoft** [comment]
Great, I will do this in my extension then. I already tried this approach just to verify that there is something going on and that Dexie is not hung, and it does appear to work (albeit very slowly). It will also allow me to display a progress bar for these long delete operations, so users can see that something is happening, at least.

Closing this issue as it sounds like a problem with the underlying IndexedDB technology and not the Dexie library. Thanks again for your advice. Aside from this one annoying issue, Dexie is working great in my extension 😄
