### ISSUE TITLE
sorting index based on integer value

### ISSUE THREAD

**Issue by 4j1th** [dfahlander/Dexie.js#385]
` var db = new Dexie('name');
	db.version(4)
	.stores({
      sentence: "&sentenceId, [sentence__authorId+sentenceChapter+sentenceNo], sentenceContent, headingContent, sentenceStarts, sentenceEnds"
      )};`

and I need to get the result sorted by sentenceNo

    `db.sentence.where('[sentence_authorId+sentenceChapter+sentenceNo]')
    .between([articleId, chapter_selected.toString(), -Infinity], [articleId, chapter_selected.toString(), '\uffff'])
    .each (function (sentence) {
    //............
    });`

but the result I get from the above query is like sorting an integer column in string format

eg: 1,11,12,13,14...

how to sort sentenceNo in integer

eg : 1,2,3,4,...

**Comment by dfahlander** [comment]
From http://stackoverflow.com/questions/40880150/indexeddb-sorting-index-based-on-integer-value/40885499#40885499:

Are you sure that sentanceNo are not stored as strings instead of numbers? IndexedDB enumerate your index in respect to its types.

If you're certain that typeof sentanceNo === 'number', the only thing I could think of would be if you're using a Safari < 10 with IndexedDBShim - theoretically, the shim could have this kind of bug, but that is just a theory.

**Comment by 4j1th** [comment]
sorry the problem isn't dexie it's caused by json (used it for bulk add) request, and the json generated from a mysql database result and mysql gives all result in string that caused the error.
