### ISSUE TITLE
Backup database support

### ISSUE THREAD

**Issue by lynxionxs** [dfahlander/Dexie.js#391]
Why is it not possible to backup the whole database?
A way to ```db.export('hellodb')``` and ```db.import(./hellodb.json)``` will be great!

**Comment by dfahlander** [comment]
The feature could fit into dexie itself, or an external tool. To keep size small, I'd prefer to have an external tool (with its own npm package or so). The code to export / import is rather simple

```js
function export(db) {
    return Promise.all(
        db.tables.map(table => table.toArray()
            .then(rows => {table: table.name, rows: rows}));
}

function import(data, db) {
    return db.transaction('rw', db.tables, () => {
        return Promise.all(data.map (t => db.table(t.table).bulkPut(t.rows)));
    });
}

```

**Comment by lynxionxs** [comment]
A native Dexie solution will be great. 
IndexedDb is missing that important feature. 
Thanks.

**Comment by VladShcherbin** [comment]
This would be an awesome feature. We will be able to sync the whole db between computers.

**Comment by nponiros** [comment]
@VladShcherbin in case you didn't know, you could also use [dexie-syncable](https://www.npmjs.com/package/dexie-syncable) to sync between computers/browsers.

**Comment by VladShcherbin** [comment]
@nponiros thanks for a suggestion. From a quick look, it uses websockets.

I need to store the *db file* to the filesystem, be able to upload it to dropbox, connect another computer to the same dropbox and select this db file as a storage. Is it possible to do this with *dexie-syncable* or any other library for dexie ?

**Comment by nponiros** [comment]
@VladShcherbin Syncable can use websockets or ajax depending on the protocol you use and the server you use. The protocol is something you would have to implement so you can decide if you want to use sockets or ajax. Of course you could use one of the sample implementations from the [samples folder](https://github.com/dfahlander/Dexie.js/tree/master/samples/remote-sync).

With Syncable you would not use dropbox. You would use a server to do the synchronization. What I do is start a server locally using node.js and sync the devices. I use https://github.com/nponiros/sync_server . The files produced by SyncServer could be uploaded to dropbox but the other device would still need to start the server to sync the data with the browser. So if you don't have a server somewhere on the internet, using Syncable is more complex (or even impossible depending on your scenario) than just backing up the database to a file but it has a better performance since you only sync changes and not everything every time.

From what I know there are no Dexie addons enabling you to do what you want to do. You can vote for this feature here: http://feathub.com/dfahlander/Dexie.js or even better implement such an addon and share it with us :)

**Comment by lynxionxs** [comment]
I do not want ``` dexie-syncable ``` . 
I just want to backup the whole indexeddb so it's not so tied to the browser. And to store the backup on the cloud.
The same reason all other database types have backup capabilities. 
Keeping decoupled scripts just to do this is not ideal. Version changes can break the scripts.
I would like it as a native feature in Dexie.js. Then Dexie.js will be complete for me.

**Comment by nponiros** [comment]
If this feature would be part of Dexie and not an addon then we shouldn't add code to actually save the file into Dexie as this will bloat it. The export function could export an object which could later somehow be saved by the user's code or sent to a server.

@lynxionxs you can vote for this feature here http://feathub.com/dfahlander/Dexie.js

**Comment by VladShcherbin** [comment]
@nponiros thanks for the detailed information. While the remote sync is nice, I also need just an export/import mechanism, preferably as a native feature. Would love to see it in Dexie.

**Comment by lynxionxs** [comment]
The ``` exportDB(...) ``` method should return an object or a json string with all the data.
Then the developer can just upload that to the cloud via Ajax. 
I'm sure it won't be that much bloat added to dexie. Backup is a standard feature in all databases. Not sure why Indexeddb neglect that.
But i need it for the desktop apps built with Electron and NW.js. So to backup application data for the users. 
I voted for it, but why should we have to vote for an expected native capability like that ?

**Comment by VladShcherbin** [comment]
@lynxionxs I also want to use it with an Electron app, didn't find a good & well maintained db with this functionality. Maybe you found another solution?

**Comment by nponiros** [comment]
@lynxionxs the vote helps us decide what to implement next as our time is limited. I am personally interested in this feature and would like to implement it but I have to find time to do it.

**Comment by lynxionxs** [comment]
@nponiros that would be awesome.
I dont mind you can take your time with it. Aslong as its added in the future.
I will make do with the hacks for now. Thanks.

**Comment by lynxionxs** [comment]
@VladShcherbin i'm using Sqlite3 with node. But it's a pain to compile for various distros.
Aswell as the hacks mentioned for Dexie.
Hopefully in the future things will be smoother.

**Comment by VladShcherbin** [comment]
@lynxionxs oh, I also thought about using sqlite but decided to google alternatives first.

Have you tried [sql.js](https://github.com/kripken/sql.js/), maybe things are better with it?

**Comment by lynxionxs** [comment]
No i hav'nt. I don't have time to learn and implement new stuff.
It would set me back too much.
I'm just going to stick with the hacks for now.

**Comment by dfahlander** [comment]
I get the point that backup/restore  is essential. However it feels like I need to reassure that using the [proposed solution](https://github.com/dfahlander/Dexie.js/issues/391#issuecomment-265097782) is not  a hack,  it's the  safe way to do it as long as your database fits into ram. It returns a Promise and captures any error. Maybe my comment there made it sound like it was a hack but it's not.

However,  the reason i don't just put it in now is that I'm thinking of some aspects like:

1. Large databases will take some time to backup and to restore as well. Some kind of progress callback would be useful. 
2. Large databases may for some systems be too heavy for ram. Maybe better to export / import to a blob than to memory 
3. Version needs to be part of the export. Import should preferably handle importing an old version db as long as there are upgraders assigned to it.

Feedback?

**Comment by dfahlander** [comment]
Also, in case db stores native objects (blobs, ArrayBuffers, ImageData,  Date etc,  they should be exported /imported correctly (think @nponiros pointed that out in the FR).

Might get some use of [typeson](https://github.com/dfahlander/typeson) to accomplish this, but that leads me to think it really should be an addon, otherwise we would increase the code size too much. Could be an addon like dexie-syncable that is maintained and tested in this repo.

**Comment by nponiros** [comment]
Maybe we can include a simple case in dexie and more complex cases (blob etc.) in an addon (preferably in this repo as @dfahlander mentioned.

I was considering that the schema should maybe also be part of the export to make sure that we are actually dealing with the correct db (tables, indexes etc.).

We also need to consider what happens when backup is used with syncable or other plugins which create tables. Do we also backup non-user tables like \_changes?

We should also wait for the new upgrade process to be merged to avoid having to migrate the backup logic.

**Comment by dfahlander** [comment]
@nponiros Agree 100%. The question is then: what would users expect from the simple version? 

* My proposed solution but with schema /version check added? (only allow imploring same version) 
* Simple progress callback?

**Comment by nponiros** [comment]
@dfahlander your proposal + version/schema check and progress sounds good to me.

I think allowing upgrades with given db upgrade functions could be rather compicated since those might execute operations which are only allowed during the upgrade phase of indexeddb (index change, store deletion etc.). The user will probably have to define extra upgrade functions just for the import. Functions which will work with javascript objects (or whatever format the import has) and not expect an indexeddb interface. If we want to use only one upgrade function, we will probably have to stud out indexeddb with something that will work with the import format. For example a store delete will have to delete from the import and not from the db so idbstore would probably have to be stubbed.

**Comment by lynxionxs** [comment]
@dfahlander i did'nt thought about the RAM issue with this feature. Since i was working with an Electron app and looking to backup the data from indexeddb when i made this issue.
Desktop apps have access to the filesystem and subprocesses. So the backup feature may be better suited in that environment. Where it can have unlimited storage size and be sent to the cloud in the background.
So i guess i did'nt thought this through enough. And data backup methods seem unnecessary now seeing how limited a browser environment is.

Sorry about that. 
You may continue with this feature if you feel so.
Thanks for your time.

**Comment by dfahlander** [comment]
@lynxionxs Electron use case is as relevant as the web for Dexie. In Chrome and Electron, it is possible to open a file for writing and streaming the content to it. This think should be investigated. For the standard Web, we only have FileReader to import a previously exported file but not to write a file as a stream (as what I'm aware of).

**Comment by lynxionxs** [comment]
@dfahlander i agree 100%.

**Comment by Tup3x** [comment]
@VladShcherbin I actually use sql.js in my Electron project and importing/exporting database is very straight forward with it (after all, it sqlite). It does increase the start up time though (compiling asm.js code takes some time). Also I'm not sure healthy the development is and if it's going to be maintained. It does work surprisingly well.

For Electron use case, exporting/importing/backup indexedDB would be really handy. If Dexie would have that feature I'd almost certainly start using indexedDB.

**Comment by CodinMoldovanu** [comment]
https://www.npmjs.com/package/indexeddb-export-import This exists and works with Dexie, it does export to JSON which is exactly what @dfahlander argued above regarding exporting different data types that don't agree to being JSONized.

**Comment by VladShcherbin** [comment]
@Tup3x I even tried to use sqlite with Electron, wanted to use `sequelize` / `knex` with `sqlite3`. Both had some problems with electron / webpack and both don't work with `sql.js`. That was the last bit with sqlite shit.

Then I tried Dexie and even found the examples for React, Electron inside. It was like a dream after sqlite mess. And you know what - I just plugged it in and there were no rain-dances with it. *It just worked*. So, I'll just use this json export/import thing above and wait for a better native solution with db versions later. 

Really appreciate the work done with the docs and examples for this project. @dfahlander , @nponiros 👍 ❤️

**Comment by Tup3x** [comment]
@VladShcherbin I'll port my database "class" indexedDB using Dexie next week. While sql.js is neat toy performance is what it is and I can see issues when the database gets bigger.

**Comment by dmarcelino** [comment]
I've just tried @Polarisation's `indexeddb-export-import` and it worked fine for my use case, so a big thanks to him!

If Dexie can be extended to support this and extra features, namely handling older version DBs, that would be great.

**Comment by dfahlander** [comment]
I'm working on an addon that will add Dexie.prototype.export() and Dexie.prototype.import(). This addon will handle not just JSON but any structured clonable types (Date, binary arrays, Blobs etc). It also has options and an optional progress callback.

The work is done in [this branch](https://github.com/dfahlander/Dexie.js/tree/dexie-export-import)

**Comment by dfahlander** [comment]
Addon is now complete. Please help me test / contribute to it:

https://www.npmjs.com/package/dexie-export-import

**Comment by dfahlander** [comment]
Regarding the discussion about whether to put this feature within dexie.js or as an addon, I have choosen to put it in an addon. Much because of its external dependencies would almost double the size of dexie.js if bundled in. And changing dexie from independant to dependant would cause major backward compatiblity issues for some users.

The arguments for having it natively within dexie are valid, but I can argue that those arguments are forfilled even if it is an addon, because:

1. Continous integration tests will run its unit tests on every commit to this repo. As part of the testing framework on browserstack, this addon will be continously tested on all supported browsers (IE11, Edge, Chrome, Firefox and Safari). This means that it is impossible to change dexie in a way that would break the addon without unit tests complaining about it. And the release script will never push to npm if not all tests pass.
2. It is maintained in the same monorepo, having the sources close to each other.
3. The addon integrates to the existing dexie API so that it feels as a natural part of the Dexie API.

In practice, this addon will be seen as a natural part of Dexie, only that you will need an extra import or script include to activate it.
