### ISSUE TITLE
Data-dependent differences in behavior between Chrome and Firefox

### ISSUE THREAD

**Issue by qoregexp** [dfahlander/Dexie.js#396]
Reading a comma-separated file, splitting and converting to numbers, then adding to the database -- one line was inadvertently missing the last value (my bug).  After the put, Chrome had the field as NaN, while Firefox had it as null (browsing the database in the developer tools).  This is a field that I am going to do a where ... sort on.  Presumably because of data type difference, the sort works in Firefox, but seems to barf partway through the sort in Chrome (the values returned are not in sorted order OR database order).  This may not be under your control but I thought I'd just mention it
[ixdbtest.zip](https://github.com/dfahlander/Dexie.js/files/652777/ixdbtest.zip)
.

**Comment by dfahlander** [comment]
Both firefox and chrome treats Number(undefined) as NaN. At least with Firefox 50.0.2, it's NaN. Maybe the developer tools shows "null" in error.

Still I get the error you describe in Chrome - that it fails to sort the result. I hunt it down to be a pure difference between how [].sort() works in Chrome from how it works in Firefox. Could repeat the issue by just sorting an plain array without involving indexedDB nor Dexie. Chrome fails to sort arrays correctly where a NaN is present.

If you'd used orderBy instead of sortBy(), you'd see that the sort order would have been correct, but it would have omitted the NaN record from the result.

Tips: Did you know that you can utilize the database sorting of different keys also when quering with a where() clause? The trick is using compound index of the filter-key and the sort key

```js
var db = new Dexie('test');
db.version(1).stores({
  patkey: '[patno+sym], patno'
});
db.version(2).stores({
  patkey: '[patno+sym], [patno+keyorder]'
});

var patno = 1;
db.patkey.where('[patno+keyorder]').between([patno, -Infinity], [patno, Infinity]).each(record => {
    console.log(arr[i].symname + " " + arr[i].keyorder);
});
```

**Comment by qoregexp** [comment]
Thanks for the quick reply.  I thought it was likely to be a Chrome 
issue but blanked on how to verify that. Thanks for the tip, also.

Regards,
Meredith
Scarlet Quince ... the Fine Art of Cross Stitch (tm)
http://www.scarletquince.com
