### ISSUE TITLE
Object store not found when trying to use table in hook

### ISSUE THREAD

**Issue by cfilipov** [dfahlander/Dexie.js#473]
I was having an issue in #372 which I thought was related to hooks and version migrations. Turns out the problem was more fundamental than that. I simply cannot access a table from with the context of a hook. I get the following error:

```
Failed to execute 'objectStore' on 'IDBTransaction': The specified object store was not found.
```

[This JSFiddle](https://jsfiddle.net/v64hgb18/6/) provides a minimal example of the problem I'm running into.

Basically, I have two tables, `friends` and `enemies`, and I create a hook on `friends` to query `enemies` whenever a `friend` entry is created/added. The call to `db.enemies.get()` results in the error above.

**Comment by nponiros** [comment]
My guess would be that the hook is running in a transaction containing only the friends table and this is why querying the enemies table fails. I don't know of any way to add the enemies table to the transaction given by the hook. Creating a new transaction doesn't seem to work. Probably because the hooks are not async.

**Comment by cfilipov** [comment]
Is this an expected behavior of Dexie? That is, hooks can only access the table on which the hook is defined? It would be good to add this to the documentation since it's not specified right now.

**Comment by student020341** [comment]
I believe based on [this](https://github.com/dfahlander/Dexie.js/issues/106) issue, something is actually amiss. 

Thanks for opening this, I thought I was going crazy... there is a similar issue in version 2 beta 10. Something has broken functionality that was present in whatever version the referenced issue is using. Unless they were using friend tables... not sure.

**Comment by dfahlander** [comment]
You can access other tables, but they need to be part of the transaction. This is done by writing a transaction block where both tables are included.

**Comment by student020341** [comment]
I started my indexdb adventures yesterday. Could you point to some example code or page that has an example of multiple tables being part of the transaction? Or are you saying I need to perform a pointless operation on any table I want to access in a hook?

**Comment by dfahlander** [comment]
The page you found is correct. But you do not register hooks there. Registering the hook will not be affected by a current  transaction.

First, you register hooks. 
Second you perform a transaction that does something with a table so that your hook is called. And when it is, your hook will only be able to operate on tables that are part of the transaction.


Are you sure you need to use hooks at all? They are pretty low level stuff. If you're just querying the db you don't need them. They are for people writing abstraction layers. If you need to make sure that whenever table 'friends' is operated on, also include table 'friendsAddresses',  you can have a look at how Dexie.Observable does that (addons/Dexie.Observable/src) by overriding _createTransaction () )

**Comment by student020341** [comment]
I see, thanks. I need to go turn my db.table into db.transaction and put multiple tables in the transaction args...

I'm not sure what I need, but the functionality I am creating is cascade delete. I posted some code above to show this. Hooks seem to be working for that, I think the api documentation says hooks are useful for implementing that?

**Comment by dfahlander** [comment]
I see! Interesting. If you're successful with this, please let us know. Might be something others would be interested in as well.

**Comment by student020341** [comment]
Unfortunately, it looks like transactions did not work for me.

```
  // delete node hook
  db.nodes.hook('deleting', function(key, record, transaction){
    // after deleting a node, go delete its associations 
    this.onsuccess = function(){
      // db2.links.
      console.log("deleting node " + key);
      console.log(transaction);
      transaction.links
        where('parent').equals(key)
        .or('child').equals(key)
        .delete();
    };
  });
```

I have a hook in db.links to log when a link/association is deleted, but it is not called. And when I look at the database, it is clear that transaction.links<...>.delete() did not execute. 

Might have to stick with multiple databases for the time being, because the example I posted previously does work. Or maybe the problem is my calling function/transaction?

```
function delete_node(id) {
      return db.transaction('rw', db.links, db.nodes, function(){
        db.nodes.where('id').equals(id).delete();
      });
    }
```

**Comment by cfilipov** [comment]
In case anyone runs into the same thing I thought I should follow up on this issue. As pointed out by @dfahlander and @student020341 you do indeed need to specify all the tables in a transaction, here's the [updated jsfiddle](https://jsfiddle.net/v64hgb18/9/).

I feel like this requirement somewhat defeats the utility of hooks. The idea is that you just modify one table and others will automatically update based on that change, having to specify the related tables in a transaction seems like a burden. For what it's worth, this at least results in an error, so if you forget to specify the tables in a transaction like the initial jsfiddle, then you get an error (at runtime, of course).

What I ended up doing was using [Dexie.Observable](http://dexie.org/docs/Observable/Dexie.Observable.html). It does not require you to specify the tables, and in my case, it was even better because Dexie.Observable observes changes *after* they are made, rather than before they are committed (hence why it does not require the transaction, I suppose). The caveat of course is that it is a separate transaction, so if you wanted the whole transaction to fail together (the operation that triggered the hook and the hook) then Dexie.Observable is probably not the right choice.

**Comment by cfilipov** [comment]
One last comment regarding the solution, and closing this issue.

While Dexie.Observable worked as mentioned above, I went back to using hooks instead. As mentioned earlier Dexie.Observable batches changes and notifies the listener long after the transaction is already over. In my case I actually did need it to be part of the same transaction. 

I don't know how I missed this before, but there is [sample code](https://github.com/dfahlander/Dexie.js/blob/master/samples/full-text-search/FullTextSearch2.js) that demonstrates how to use hooks with multiple tables without manually wrapping each operation in a transaction as in @student020341's solution.

**Comment by student020341** [comment]
It looks like the solution linked is to override createTransaction and push the tables you need into storeNames. Is that accomplishing the same thing but without explicitly including the tables in the transaction blocks?

**Comment by cfilipov** [comment]
Exactly. 

Instead of this:

```swift
function delete_node(id) {
  return db.transaction('rw', db.links, db.nodes, function(){
    db.nodes.where('id').equals(id).delete();
  });
}
```

You do this:

```swift
db.nodes.where('id').equals(id).delete();
```
