### ISSUE TITLE
Call to setImmediate in asap function (utils.js) throws error

### ISSUE THREAD

**Issue by glaucoaq** [dfahlander/Dexie.js#485]
Scenario: React application depending upon Dexie.js version 1.5.1, built with webpack  1.9.11, running in Debian Jessie 64bits, Chrome 56. An error is raised during application statup (_webpack_require) when loading Dexie.

The error occurs in asap function, declared in utils.js:

> cannot call method 'bind' of undefined

This occurs because `setImmediate` is not available as a global variable, although it exists as `_global.setImmediate` (which its presence is tested against to).

I am about to send a pull request with a proposed fix, already tested.

**Comment by dfahlander** [comment]
Thanks for finding this and your effort to with the PR. Really appreciate PRs but I have two concerns with this one. The fix should though go into "master-1" and not "releases-1". "master-1" is the master branch for Dexie 1.x. "releases-1" is only committed to by the release script. (Not documented, so you couldn't know ;)

However, I need to understand how this error can possibly occurs. If _global is the global object as we expect it to be (window on browsers), I could not imagine any possible way for _global.setImmediate to be different from a plain setImmediate. Can you explain why your fix (adding "_global." in front of "setImmediate") could fix the issue? The only thing I could think of is that _global is not pointing to the real global object, and if so, there's another problem somewhere. ?

**Comment by glaucoaq** [comment]
Hi, David.
As far as I could see, the plain `setImmediate` is not available due to "strict mode" and eval(). I think it should have been introduced to global scope by `setimmediate` library, at the time it was required.
However, Webpack builds everything to run using eval - including Dexie.js and setimmediate (library) - and in strict mode. Therefore, it is not possible to `setimmediate` introduce the function as global.

> Second, eval of strict mode code does not introduce new variables into the surrounding scope. In normal code eval("var x;") introduces a variable x into the surrounding function or the global scope.

[Simplifying variable uses](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Simplifying_variable_uses).

On the other hand, it is possible to define and access new properties in the global object (Window, in this case) as long as you qualify it.

Finally, my browser does not support `setImmediate` function. My colleague started using Dexie.js a few weeks ago and never experienced any problemas. Just when we tried to compile and run in other environments (mine at first) the problem had appear.

**Comment by dfahlander** [comment]
Thanks for the excellent explanation! Makes sense. I wonder which would be the best way to deal with these things. A common used patterin is to check `typeof setImmediate !== 'undefined'` rather than checking the existance on the global object. If I would change these kind of tests to a typeof check instead, it would, in your case, never find it, but fallback to setTimeout, which would be ok, and maybe less error prone and independant on the polyfill. I'm leaning towards using that kind of check instead. Or what would you say?

**Comment by dfahlander** [comment]
Fiddling a little with this. Seems that if you eval `self.someVar = 3` in strict mode, it will still set the var on the global object and you will be able to access it as just `someVar`. So it seems as webpack require has set "self" to something other than window before loading Dexie. I could be wrong, but I do not get how this can be happening. Anyway, since it obvously IS happening, we'd better adjust for it.

**Comment by glaucoaq** [comment]
>  Or what would you say?
I'm not sure about the benefits/drawbacks of setImmediate and setTimeout as used by Dexie.js - for example, maybe setImmediate it's so much better than setTimeout that even a pollyfill worth it. Then I wouldn't dare to put my two cents in.

Anyway, to be honest, I don't think webpack replaces "self". Using self to declare globals is a common practice (although not recommended, but sometimes, required) for webpack, and I really never heard any mention to "other thing in self". I think we'd need to dig deeper to find out what is happening.

**Comment by dfahlander** [comment]
I'm fine with your PR, since it should solve it. However, I'm not satisfied with not understanding how this happens. The reason we to use `self` rather than `window` is that it works the same across DOM and workers. For node we use `global`. 

The only possible reasons I could think of would be:

1. When webpack's require calls eval(), its local scope has an `setImmediate` symbol that is set to `undefined` and overrides the global symbol.
2. When webpack's require calls eval(), its local scope has a `self` symbol that is set to something else than the global object.
3. A possible minor chance, however inlikely ;), would be that there's a subtle bug that I've missed here.

Would you be able to put a breakpoint when this happens and inspect the call stack? Understand if you have not time. Just curious to know ;)

**Comment by glaucoaq** [comment]
I have compared Webpack generated code before and after my change and I think I got it.

Webpack decorates every module with something that it calls _WEBPACK VAR INJECTION_ - a function call with a `global` parameter (used to catch anything you exported) and (apparently) a parameter for every global variable you have mentioned in your code. The way that such parameters are declare, they are available to your module code as if they were globals, so your code works seamlessly in _stric mode_.

When this _WEBPACK VAR INJECTION_ is called, it does "the best it can" to find the actual parameter. In the case of `setImmediate` the value is coming from _timers-browserify_ package, but it is actually using another package to inject `setImmediate` (and `clearImmediate`) function: _setimmediate_ (not really surprising). This one do its job right and set `setImmediate` as a window property. 

That would be great, but it seems that _setimmediate_ does not export `setImmediate` and _timers-browserify_ has the following code at [main.js](https://github.com/jryans/timers-browserify/blob/master/main.js):

```
require("setimmediate");
exports.setImmediate = setImmediate;
exports.clearImmediate = clearImmediate;
```

Since the only library that webpack finds to export a `setImmediate` function is _timers-browserify_ itself, it creates a auto-dependency that is never resolved. Thus, the global symbol `setImmediate` will always be `undefined` and `self.setImmediate` will be always available.

When I put the `_global` qualifier, webpack has stopped injecting `setImmediate` (since there is no global var at all) and the problem disappeared.

Maybe we could send a PR to _timers-browserify_ guys to put a `self` before the left-hand sides. :-)

**Comment by glaucoaq** [comment]
By the way, you hit the bull's eye at the 1st option.

> 1. When webpack's require calls eval(), its local scope has an setImmediate symbol that is set to undefined and overrides the global symbol.

**Comment by dfahlander** [comment]
Wow 💯, that was an impressive investigation. It fed my curiosity and makes me sleep better.
Thanks!

**Comment by xhinking** [comment]
Interesting investigation and same problem here : ( 
@dfahlander I noticed that glaucoaq's PR was merged but not being published. Can you release a new version (maybe 1.5.2) to npm? Thanks.

**Comment by dfahlander** [comment]
I'll try to releasing a new 1.x version after summer. However, I strongly promote going over to 2.x beta for this and other reasons. 2.x beta has been out long and can be consider stable. There are just a few minor things in need to get finished before 2.x becomes 'officially' stable.
