### ISSUE TITLE
Between clause on a compound index

### ISSUE THREAD

**Issue by jim-76** [dfahlander/Dexie.js#599]
Hi,

I am trying to apply a between clause on each part of a compound index. In the example below, I would expect the query to return no results, since the `lat 5.5 is between 5.0 and 6.0`, but the `lng 5.5 is not between 6.0 and 7.0`. However, it only applies the between clause on the first field of the index and seemingly ignores the second field and returns the inserted object.

```
          var db = new Dexie("test");
          db.version(2).stores({
              data: 'id++,[lat+lng]'
          });
          db.data.add({lat: 5.5, lng: 5.5}).then(function() {
            return db.data.where(['lat', 'lng'])
              .between([5.0, 6.0], [6.0, 7.0], true, true)
              .toArray()
          }).then(function(res) {
            console.log(res);  // Expect nothing here, but received the object back
          }).catch(function(e) {
            console.log(e);
          });
```
I also put it in a jsfiddle https://jsfiddle.net/j8746j9p/

I tried to follow the sample here http://dexie.org/docs/Table/Table.where().html,
Specifically the query for 'Find friends named David with age between 23 and 43'. 

I also tried replacing the where clause with `db.data.where('[lat+lng]')` as shown on here http://dexie.org/docs/API-Reference#query-items to the same results

Any help would be appreciated. Thanks

**Comment by dfahlander** [comment]
Hi @jim-76. The reason it doesn't return what you expect is because a compound index can bee seen as a simple concatenation of the two keys, so your query would basically return all items between 5.0 <= lat <= 6.0  but NOT items where (lat == 5.0 and lng < 6.0), and NOT items where (lat == 6.0 and lng > 7.0).

A compound index is typically most useful to query in a between() clause when the leftmost parts are constant and the range is only flexible in the rightmost part.

In your use case, I would recommend using just one of the indexes and filter out the other part using [Collection.filter()](http://dexie.org/docs/Collection/Collection.filter()). Also advanced databases have this kind of compound indexes, so they couldn't use the compound index for that kind of query.

**Comment by dfahlander** [comment]
A sample of how you could rewrite the query:

```js
var db = new Dexie("test");
db.version(2).stores({
  data: 'id++,[lat+lng]'
});
db.version(3).stores({
    data: 'id++,lat'
});
db.data.add({lat: 5.5, lng: 5.5}).then(function() {
  return db.data.where(['lat', 'lng'])
    .between(5.0, 6.0, true, true)
    .and(x => x.lng >= 6.0 && x.lng <= 7.0)
    .toArray()
}).then(function(res) {
  console.log(res);  // Expect nothing here, but received the object back
}).catch(function(e) {
  console.log(e);
});
```

**Comment by jim-76** [comment]
Thanks for the explanation.

**Comment by kys2** [comment]
Would anybody happen to know what I should do in the following situation?

I'm recording browsing history and my query is trying to get all events that overlap with today, that is events whose beginning OR ending time is lands within today. Like above, it's filtering by the first two attributes (`url` which is fixed and `begin` which varies) but ignoring the third (`end`, also varies). As a result, I'll get all intervals where `begin` lands within today, but if I have an interval that starts yesterday but ends today, it's ignored.

```javascript
const db = new Dexie("database");

db.version(1).stores({
	history: "[url+begin+end]"
});

// Beginning and end of today.
let today_begin = new Date();
today_begin.setHours(0);
today_begin.setMinutes(0);
today_begin.setSeconds(0);
today_begin.setMilliseconds(0);
let today_end = new Date(today_begin);
today_end.setHours(23);
today_end.setMinutes(59);
today_end.setSeconds(59);
today_end.setMilliseconds(999);

// Get all of the events that overlap with today, that is events which have a beginning or ending time some time today.
db.history
		.where("[url+begin+end]")
		
		.inAnyRange(
			[
				[["github.com", today_begin, -Infinity], ["github.com", today_end, Infinity]],
				[["github.com", -Infinity, today_begin], ["github.com", Infinity, today_end]]
			],
			{
				includeLowers: true,
				includeUppers: true
			}
		)
		.toArray(array => {...});
```

Originally I was using Table.filter(), but it was giving relatively poor performance of T(R) so I was trying to reduce it to B(index(R)) by indexing it so Dexie could just do a B+Tree index range scan.

Since I'm looking at dates both near the beginning and end of the recorded browsing history, indexing just `begin`, doing `where("begin").belowOrEqual(today_end)`, and then doing `Collection.filter()` or the opposite with `end` doesn't yield much of a performance benefit when scanning the extremes of the browsing history.

Is there a way I can use compound indexes to do this or can I only use Table.filter() to get the result I want?
