### ISSUE TITLE
Safari can't handle identical keys across collections

### ISSUE THREAD

**Issue by listrophy** [dfahlander/Dexie.js#65]
Reported here: http://www.raymondcamden.com/2014/09/25/IndexedDB-on-iOS-8-Broken-Bad

What to do? The proposed solution is to use namespaced keys. Should Dexie.js provide a way to namespace the keys? It's only an issue on Safari, but that means any hybrid application that runs on iPhone has to deal with it.

[Live Example](http://s.codepen.io/listrophy/debug/jEYedj?) ([source](http://codepen.io/listrophy/pen/jEYedj)) Notice how adding the `thing`, the `widget` disappears.

**Comment by dfahlander** [comment]
Thanks for sharing, that's serious stuff :)  I tried your sample on chrome but had to change the script include to https://rawgit.com/dfahlander/Dexie.js/master/dist/latest/Dexie.js to make it work (will serve it will correct content type).

I would not like to include a fix directly in Dexie but it would be great if it could be fixed by creating a polyfill that fixes the issue by rewriting IDBObjectStore.prototype methods to prefix and unprefix keys. But that is not a simple task because one would need to intercept get() and onsuccess callbacks from openCursor() etc. But it's doable.

Another solution for Safari may be to use the [indexedDBShim] instead if it works better than the native (http://nparashuram.com/IndexedDBShim/) but to make it work on the newest Safari browser you would have to change the __useShim() method in the source of the shim. See Issue #63.

**Comment by listrophy** [comment]
Ah. Right. Forgot about that cross-browser MIME issue. I fixed the codepen. Thanks!

So, I don't exactly expect Dexie to have this as a normal feature. But perhaps we could have an addon and also make some architecture choices to make such an addon easier to write?

Perhaps instead there could be an easy way to use a uid generator, whether that's a guid generator or an autoincrementing id-number vending table.

**Comment by dfahlander** [comment]
Good thought. There's a guid generator included in Dexie.Observable.js that would help working around the issue. The code could be pulled out as its own plugin.

If we go the path by prefixing all keys generically, and hiding that for the API user, it would be almost easier to override the default behaviour of IDBObjectStore.prototype etc I think. Unless as you suggested, to remake the architecture to simplify writing such a plugin, which would be a good thing, but (for me at least) not possible to do in the nearest future.

Crud hooks could not solve the issue as they work today. An addon would need to override dexie methods such as db.WriteableTable.prototype.put(), db.WriteableTable.prototype.add(),db.WriteableTable.prototype.get(), db.WriteableTable.prototype.delete(), db.WriteableCollection.prototype.modify() and db.Collection.each().

**Comment by dfahlander** [comment]
As of current status of the native indexedDB support, it is better to use the WebSQL shim (IndexedDBShim) than the native. However, that shim is not 100% standard compatible so there might still be some minor issues but not as severe as Apple's own bugs in its implementation of indexedDB.

From now on, to use the shim instead of the native IDB support, just include the [indexedDBShim](https://rawgit.com/axemclion/IndexedDBShim/master/dist/IndexedDBShim.min.js) before including Dexie. See #77 .
