### ISSUE TITLE
I wrote dexie-batch, a tiny supplemental lib to improve bulk read speed

### ISSUE THREAD

**Issue by raphinesse** [dfahlander/Dexie.js#650]
In #606 you mentioned interest in dexie-based libs. Well, some time ago, I wrote [`dexie-batch`](/raphinesse/dexie-batch) a tiny supplement to Dexie.js to improve bulk read speed when needed. I just recently polished it up a bit.

Getting a lot of data at once can result in the error *Maximum IPC message size exceeded*. Getting single records with Dexie's regular `Collection.each()` will greatly reduce throughput, which is bad when handling a lot of records. `dexie-batch` alleviates the problem by providing an `each` method that fetches records in batches of configurable size.

Even though the project already does a great job in the wild, there are still some todos. Mainly:
- Support for less modern browsers (i.e. `babel` build)
- More documentation

I appreciate any feedback that goes beyond that.

Do you plan on listing/promoting related libs somehow?

**Comment by dfahlander** [comment]
Many thanks! I listed your addon on [this page](http://dexie.org/docs/DerivedWork). Feel free to change the way it's promoted there by editing the page if you want.

I looked at the code and it seems it uses offset/limit to divide the chunks. This would be efficient especially for the first chunk, as it will result in getAll(limit). However, chunks following the first chunk won't be able to utilize getAll() since it has no offset parameter. There would be ways to fix this but not very easily. If we introduced a paginator API on dexie that could re-launch getAll() on a KeyRange instead of using offset/limit, your addon would be able to use that instead. The principle would only work on simple queries (as it does now as well), such as between(), below(), above() and equals() (queries that maps directly to an IDBKeyRange). By inspecting the last key in the retrieved page / chunk, the next page could alter the keyrange and do getAll() again.

I will probably not have time to implement a paging API so soon. I'm currently spending the time on dexie with a typescript-rewrite that will be finished quite soon. But maybe your addon could implement this without the paging API, even though you would have to inspect the _ctx property of the collection to be able to alter the keyrange for subsequent chunks.

**Comment by dfahlander** [comment]
We also have PR #465 to do, which basically means promoting addons in README as well. Taking this into account also.

**Comment by raphinesse** [comment]
Thanks a lot for your comprehensive feedback and the promotion!

The good thing is: in the applications I tested the lib with, It already outperformed a naive `each` by lengths (getting all records at once was not possible due to IPC size limitiation of Chrome).

Still, it is good to know how further speedup can be achieved. In fact you got me curious. So when I have some time on my hands again, I'm going to write a benchmark to compare performance with a bare metal implementation using `getAll` to see what is actually to be gained from that.

PS: I'm fine with closing this issue. It was intended to inform you of the existence of `dexie-batch` and that is done.
