### ISSUE TITLE
Using Dexie.js inside Chrome App

### ISSUE THREAD

**Issue by le0pard** [dfahlander/Dexie.js#66]
Hello.

I am trying to use Dexie.js inside Chrome App. But inside Chrome app not available localStorage. In this case I get error about this: http://monosnap.com/image/E9hpQMgTXDgGzIpfVyecfJmExRZsYR

Does it possible to use Dexie without localStorage?

**Comment by dfahlander** [comment]
The reason localStorage is even used is to support [Dexie.getDatabaseNames()](https://github.com/dfahlander/Dexie.js/wiki/Dexie.getDatabaseNames()) for non-chromium browsers (Chrome and Opera has a native function to map to, but on other browsers we keep track of the global database list in a localStorage variable).

Due to lazy coding, localStorage were updated and managed also on chromium. Please use the latest version of src/Dexie.js instead which will not try to use localStorage where not needed.

**Comment by le0pard** [comment]
Hello. Still have error in Chrome App, because it continue call `window.localStorage` on this line: https://github.com/dfahlander/Dexie.js/blob/master/src/Dexie.js#L3094

I checked, this can help:

```js
Dexie.dependencies = {
  indexedDB: window._indexedDB || window.indexedDB || window.mozIndexedDB || window.webkitIndexedDB || window.msIndexedDB,
  IDBKeyRange: window._IDBKeyRange || window.IDBKeyRange || window.webkitIDBKeyRange,
  IDBTransaction: window._IDBTransaction || window.IDBTransaction || window.webkitIDBTransaction,
  Error: window.Error || String,
  SyntaxError: window.SyntaxError || String,
  TypeError: window.TypeError || String,
  DOMError: window.DOMError || String,
  localStorage: ((typeof chrome !== "undefined" && chrome !== null ? chrome.storage : void 0) != null ? null : window.localStorage)
};
```

**Comment by dfahlander** [comment]
Thanks. Merged your suggestion in. Passes unit tests.
Please retest and verify it's a working solution and I'll close the issue.
Will be part of next release.

David

**Comment by le0pard** [comment]
Thanks @dfahlander . All works.

**Comment by DinkoMiletic** [comment]
Hello,

I have problem in xul application. It's calling window.localStorage which is not avaiable in xul.

If you don't need localStorage as a fallback, you can use this as a workaround:
```
// for dexie.js to work :(
        window.chrome = {
            storage: 'placeholder'
        };
```
