### ISSUE TITLE
Possible compound primary key bug

### ISSUE THREAD

**Issue by SourceBoy** [dfahlander/Dexie.js#700]
Dexie Version: dexie@2.0.3/dist/dexie.min.js
Chrome: 61.0.3163.100

While attempting to retrieve data via compound primary key, which seems to be set correctly by following examples on [http://dexie.org/docs/Compound-Index](http://dexie.org/docs/Compound-Index), I got a SchemaError described below.

This db is newly created, and it's the only version. I tested it several times and the results were the same.

![screenshot_2018-05-23_03-50-20](https://user-images.githubusercontent.com/791200/40410786-943c6b62-5e3c-11e8-9aa5-20710f0edaa3.png)

Data and key seem to be stored correctly according to Chrome console.

**Comment by dfahlander** [comment]
Thanks! Verified. Solving now.

**Comment by dfahlander** [comment]
Sorry, was a little fast with verifying. A wrote a unit test that should verify the issue but it turned out to function as expected (no issue could be verified).

One reason for you seeing this error could be if your local DB schema is not in sync with the declared schema. To work around that, try deleting the DB in browser and run your code again. If that is the case, it may have been a result of changing the primary key (which is not supported).

Please confirm your test works after deleting db. If not, I'd need a repro script/page or PR to a unit test.

**Comment by dfahlander** [comment]
Thanks. It turns out it triggers only when dynamically opening the DB and when also there are exacly two propertys in the index (not three).

**Comment by dfahlander** [comment]
Ok, this is a bug in dexie@latest (2.x) but has already been solved in master while I rewrote the entire code into typescript (dexie@next).

So I will close the issue as was already fixed.

To get the fix , use `npm install dexie@next` or else you could also work around the bug by defining db.version() always instead of opening it dynamically. You don't actually need catching NoSuchDatabase. See [Creating Database vs. opening existing](http://dexie.org/docs/Tutorial/Understanding-the-basics#creating-database-vs-opening-existing).

**Comment by SourceBoy** [comment]
Thanks for the pointer. So do we always run the declarative `db.version(/*n*/).stores({/* ... */})` like the code below?
```javascript
'use strict';

const dbName = 'testDb';
const db = new Dexie(dbName, { autoOpen: false }); 

db.version(1).stores({
  foo: '[fid+uid]'
});

db.open().then(() => {
  return db.table('foo').bulkPut([{
    fid: 'abc', uid: 'xyz'
  }]);
}).then(() => {
  return db.table('foo').where({
    fid: 'abc', uid: 'xyz'
  }).first();
}).then(console.info).catch(console.error);
```

**Comment by dfahlander** [comment]
Yes, and other benefits always declaring db are that you :

1. don't need to call or wait for db.open()
2. may call db.foo instead of db.table('foo')
