### ISSUE TITLE
Filtering by date

### ISSUE THREAD

**Issue by erkidhoxholli** [dfahlander/Dexie.js#748]
I am trying to filter records by date column, but it doesn't seem to be working.
This is what I am currently doing:
`db.table('messages').where('date').between(dateFrom, dateTo)`

The date is already saved as 'date' type in the database. Also dateFrom and dateTo are date objects as well.
How have you guys approached filtering by date ?

**Comment by dfahlander** [comment]
What you describes seems to be correct and should be working. The Date type is indexable. 

In order to understand why it's not working for you, I think we need to see the surrounding code. The best would be if you could create a jsfiddle or similar that reproduces the issue, and I think we could help out getting to the bottom with the problem

**Comment by dfahlander** [comment]
Closing this as no response
