### ISSUE TITLE
HTML5 web worker support?

### ISSUE THREAD

**Issue by cosecantt** [dfahlander/Dexie.js#76]
Hi there. I would like to know if this wrapper works inside the web worker? If not, adding this feature would greatly be helpful. Thank you.

**Comment by dfahlander** [comment]
Hi! I have not tested it from a web worker but I understand that it would be important use case. Having that said, I believe there are good chances that Dexie would work in a web worker if including it as requirejs module. It is written to adapt to both window- and non-window environments by using "this" instead of window for global scope and all external dependencies are picked from a local "window" variable that actually is initiated from "this" at global scope, which in a web worker would be DedicatedWorkerGlobalScope.

Therefore I hereby ask the community to test that out and report back on this issue whether Dexie is supported from a web worker environment or not. If not, I will be helpful correcting what is needed to be corrected to make it work.

**Comment by cosecantt** [comment]
Hi David,
I tried to import the scripts in web workers and got the following error:
Dexie.js:3098 Uncaught ReferenceError: window is not defined

**Comment by dfahlander** [comment]
Thanks for testing! Suppose you were using dist/latest/Dexie.js. If so, it seems that we'd have to change the way it detects non-window environments.

**Comment by dfahlander** [comment]
I am creating a unit test for it now and I got the same error. Solution hopefully on its way...

**Comment by dfahlander** [comment]
Solution checked in. Please try it using src/Dexie.js because it is not yet released to dist.

**Comment by cosecantt** [comment]
Hi David,
I did a quick test. It worked by using require.js. Without require.js it did not work while it was working within the main thread. Any solutions for that? Anyway I will do more checks and inform if any issues found. Thank you!

**Comment by dfahlander** [comment]
Are you sure? My unit test did not use requrejs. I just did importScripts("src/Dexie.js") in the worker and then I could start using it

**Comment by cosecantt** [comment]
Sorry. I think it was my mistake. I was using dexie in setInterval function and the first was empty I did not wait until the second interval. It was fine from the second interval. Many thanks.
