### ISSUE TITLE
[dexie-observable] 'blocked' event fires when trying to delete database

### ISSUE THREAD

**Issue by atomrc** [dfahlander/Dexie.js#787]
[Only on Chrome] 
Here is a simple scenario that triggers the `blocked` event:

```javascript
import Dexie from 'dexie';
import 'dexie-observable';

export default function launch() {
  const db = new Dexie('mydb');
  db.version(1).stores({});

  db.on('blocked', console.error);

  db.open();

  setTimeout(() => {
    db.delete(); // this will trigger the 'blocked' event
  }, 1000);
}

```

Now If I remove the `import 'dexie-observable`, the event is not fired anymore on deletion.

Any idea?

Thanks for your help

**Comment by dfahlander** [comment]
The "blocked" event can fire temporarily if a deletion or upgrade takes more than a couple of milliseconds due to ongoing transactions or other IDBDatabase instances holding a connection to it. Even if a short-lived transaction is temporarily delaying a delete operation, the blocked event will fire.

The reason can be that observable is busy with a transaction while deletion takes place (as dexie-observable periodically queries the _changes table).

So the 'blocked' event is normally not an issue unless the delete operation also takes time to complete.

**Comment by atomrc** [comment]
Hey @dfahlander thanks for a fast and complete answer. 

I decided to go and ignore those `blocked` event if the `dataLoss` property is set to `none`. Do you think it's a valid reason not to log it as an error? 

Thanks again.

**Comment by bennyn** [comment]
> The "blocked" event can fire temporarily if a deletion or upgrade takes more than a couple of milliseconds due to ongoing transactions or other IDBDatabase instances holding a connection to it.

@dfahlander Is it possible from the outside to detect when a Dexie instance is ready to take new tasks so that I can call [db.delete](https://dexie.org/docs/Dexie/Dexie.delete()) without getting a "Dexie.delete was blocked" warning?

**Comment by dfahlander** [comment]
@bennyn The only possible way to detect if another connection is holding on to the schema, is to execute a database upgrade or deletion and listen to the blocked event.
