### ISSUE TITLE
Broken promise implementation

### ISSUE THREAD

**Issue by Nilos** [dfahlander/Dexie.js#82]
The promise implementation used by this library is broken and does not conform to the Promises/A+ standard (https://promisesaplus.com/)
The broken part in question is the then-function. If this function is called multiple times, especially after the promise has been resolved, only the first registered onFulfilled-callback will be called.
I would suggest switching to a proven promise implementation instead of an own.
If I got anything wrong here, don't hesitate to correct me :)

**Comment by dfahlander** [comment]
Dear Nilos,

Your claim about the "brokenness" really surprises me. I just tested it and could not reproduce it. Here's my simple try to reproduce it:

```
var Promise = Dexie.Promise;
var p = Promise.resolve(1);
p.then(function (x) {
    console.log("Promise resolved first time");
    p.then(function (y) {
        console.log("Promise resolved second time");
    });
    p.then(function (y) {
        console.log("Promise resolved third time");
    });
    p.then(function (y) {
        console.log("Promise resolved forth time");
    });
});
```
I get all the four console printouts, so obviously I cannot have understood the issue right?! Please show me code that reproduce it and I'll be happy to fix it.

I would also like to explain some basics about IndexedDB that you are probably not familiar with due to the "suggestion" of yours. Dexie's implementation of Promise is needed due to an incompatibility between IndexedDB and default Promise/A+ implementations (https://github.com/promises-aplus/promises-spec/issues/45). IndexedDB transactions auto-commit upon any setTimeout() or setImmediate(). So any library that want to offer the transaction capabilities of indexedDB and pair it with Promise would suffer from this. If you find a better way to incorporate indexedDB transactions into existing promise implementations, I would be more than happy to hear about it.

Hope to hear from you soon again.
David

**Comment by Nilos** [comment]
Sorry my bad, you are right :(
Some external module in my setup was overwriting setImmediate.
Sorry!
