### ISSUE TITLE
Compound index returns empty list on `uniqueKeys`

### ISSUE THREAD

**Issue by m90** [dfahlander/Dexie.js#868]
I am trying to get the unique keys for a compound index and am running into some situations where there are no keys returned at all even when data is in the index.

The code I am using is relatively simple:

```js
table
	.orderBy('[prop+nested.prop]')
	.and(function (item) {
		// some filter condition regarding timestamps
	})
	.uniqueKeys(function (keys) {
		// this will be empty in some (not all strangely) cases, even
		// when calling `keys` will yield results
	})
```

Unfortunately I have a hard time finding out why this only happens on some datasets and not all, so I cannot really provide a reproducible example right now. I might simply be doing something wrong.

**Comment by m90** [comment]
To further illustrate what I am trying to do, this is what gives me the results that I expect:

```js
table
	.orderBy('[prop+nested.prop]')
	.and(function (item) {
		// some filter condition regarding timestamps
	})
	.keys(function (keys) {
		var pairs = keys.map(function (pair) {
			return JSON.stringify(pair) 
		})
		var uniqueKeys = _.unique(pairs).map(function (string) {
			return JSON.parse(string)
		})
		// this gives me an array of unique key pairs now that
		// match with what's in the database
	})
```

**Comment by dfahlander** [comment]
I think the issue could be that the filter (and() callback) would not have access to the entire item when the collection.keys() is being used. This is of course not as expected and should be solved within Dexie. When using keys(), primaryKeys(), eachKey(), etc, filters do not work as expected because Dexie uses a keysOnly mode on the cursor so it does not have the value to provide it to the filter callback. I think the bugfix I would need to do is to disable the keysOnly mode when a filter is applied.

One workaround would be to use toArray() instead of keys() and then map out the keys from the result. That would practically have the same performance as if the issue was solved. Maybe better actually, because the native IDBIndex.getAll() method will be used instead of using a cursor.

```js
table
  .orderBy('[prop+nested.prop]')
  .toArray(values => values.filter(v =>
    v.timestamp > someThing // ... or you custom filter
  ));

```

I you want to be sparse on memory consumption, you might still want to use the and()/filter() method on the Dexie collection instead of filtering the entire array afterwards.

```js
table
  .orderBy('[prop+nested.prop]')
  .filter(v =>
    v.timestamp > someThing // ... or you custom filter
  ).toArray();

```

**Comment by dfahlander** [comment]
Sorry, I missed your point: You need to get the unique combinations of [prop+nested.prop]. 

So, I think the and() filter is the problem anyhow. If you want all unique combinations of [prop+nested.prop] without filter, the solution would be `table.orderBy([prop+nested.prop]).uniqueKeys()`. But that specific feature of IDB cannot be combined with a filter unless you have the timestamp as part of the query

```js
table.where([timestamp+prop+nested.prop])
  .above([someTime, -Infinity, -Infinity])
  .uniqueKeys()
```
Problem with that query is that every new timestamp would invalidate the uniqueness of [prop+nested.prop].

In your case, there might be a need for a unique() method on Collection (not uniqueKeys()). This would be possible with IDB, but the result may not be what you'd expect. For example if you'd have the following data:

```js
[{
  id: 1,
  prop: 1,
  nested: {prop: 1},
  timestamp: "2017-01-01"
}, {
  id: 2,
  prop: 1,
  nested: {prop: 1},
  timestamp: "2019-07-03"
}]
```
A unique iteration on [prop+nested.prop] would only yield the first entry. If your filter checks that timestamp > "2019-01-01", the key will be filtered away because the unique iteration will only land on the first row (by primary key) of each unique key.

So maybe you will still end up having to check the uniqueness using underscore. Maybe you could use IDB index to filter the timestamp instead?

**Comment by m90** [comment]
Thanks a lot for these super detailed insights, that helped me a lot in order to understand what is happening. I think adding the timestamps to the index(es) is a good idea anyways as basically all queries I do will be scoped to some timerange.

I'll try to see where it takes me and add it to this issue so others can find it too.

**Comment by m90** [comment]
So I got my counting of unique keys in the compound index working in a good way by doing this:

```js
function uniqueKeysAt (index) {
  return function (keys) {
    return _.unique(keys.map(function (pair) {
      return pair[index]
    })).length
  }
}

var uniqueNestedProps = table
  .where('[timestamp+nested.prop]')
  .between([lowerBound, Dexie.minKey], [upperBound, Dexie.maxKey])
  .keys(uniqueKeysAt(1))
```

which feels ok from an API perspective as well as from a performance one. Thanks for your input on this.
