### ISSUE TITLE
Angular and Zonejs

### ISSUE THREAD

**Issue by Neuroforge** [dfahlander/Dexie.js#939]
Hello,

Firstly, thank you for all of the work on Dexie. It's wonderful.

We are using Angular, and other issues suggest that zonejs can cause issues when reading from the DB.

https://github.com/dfahlander/Dexie.js/issues/163
https://github.com/dfahlander/Dexie.js/issues/905

Are there any straight forward solutions for Angular? We're seeing some really slow reads but it's intermittent and tbh i do not fully understand this.

Regards

**Comment by dfahlander** [comment]
Angular will do change detection on every event. Since some IDB queries will generate one event per result object, a result of 10,000 items will also generate 10,000 unnecessary change detection calls. This is avoided whenever Dexie can use the optimized IDBIndex.getAll(), IDBIndex.getAllKeys(), IDBObjectStore.getAll() or IDBObjectStore.getAllKeys(). Typically this is the case if you avoid using each(), case-insensitive operators and stick to tpArray() and the plain key range operators above(), below(), equals(), between() and startsWith().

There should also be possible to configure zone to ignore the IDB events and instead rely on promise resolving instead. If anyone would help out with providing such an optimization targeting Dexie+Angular, that would be great! Pull requests, or stand-alone libs to fix this would be great!

**Comment by Neuroforge** [comment]
Wonderful. Thank you for the response. We will try to use the suggestions that you have made here.

IDBObjectStore.getAllKeys()

and 

each()/filter() are the main issues in our code, based on what you have said.

We use....

get()
where()
anyOf()
each()
equals()
update()
filter()
first()
put()

**Comment by dfahlander** [comment]
For the current version of Dexie, my recommendation would be:

* Use the bulk... methods whenever possible rather than getting / adding / putting one-by-one. 
* Avoid anyOf() and use Promise.all(()=>... equals()) instead. This recommendation applies only to current version (2.x and 3.0). Might be a more optimized version in 3.1.
* Avoid each totally. Prefer toArray().
* Avoid filter(). Prefer filtering by hand the result from toArray().

The optimization was filed in #127 and that issue contains some comments related to it.

**Comment by dfahlander** [comment]
An example of replacing anyOf:

Instead of:

```js
await db.friends.where('name').anyOf("Foo", "Bar", "Baz").toArray() 
```

Do:

```js
flatten(await Promise.all(["Foo", "Bar", "Baz"].map(nameToFind => db.friends.where({name: nameToFind}).toArray())));
```

**Comment by Neuroforge** [comment]
Thank you.
