### ISSUE TITLE
Easy way to check schema

### ISSUE THREAD

**Issue by stutrek** [dfahlander/Dexie.js#950]
Is there an easy way to determine whether or not the schema passed in to `version(x).stores` matches what's currently in IndexedDB?

I would like to check this a delete the database if it doesn't match.

**Comment by dfahlander** [comment]
It's a pitty dexie still makes a diff between declared schemas only instead of diffing the actual schema and provide the upgrades according to that. This is something I plan to fix in a later version unless some nice person would do a PR. But for now, I can understand the need you describe in case declared versions are not perfect aligned with what has been released. This is also discussed in #942 .

To answer your question, you can do what you describe by opening the database in [dymanic mode](https://dexie.org/docs/Dexie/Dexie.open()#sample-dynamic-mode) and compare the tables and their schemas with the declared schema.

```ts

function getCanonicalComparableSchema (db) {
  return JSON.stringify(db.tables.map(table => ({name, schema}) => ({
    name,
    schema: [schema.primKey.src, ...schema.indexes.map(idx => idx.src).sort()].join(,)
  }).sort((a,b) => a.name - b.name));
}

function isDeclaredSchemaSameAsInstalled(db) {
  const declaredSchema = getCanonicalComparableSchema(db);
  return new Dexie(db.name).open().then(dynDb => {
    const installedSchema = getCanonicalComparableSchema(dynDb);
    return declaredSchema === installedSchema;
  });
}

const db = new Dexie(yourDbName);
db.version(x).stores({...}); // Your version and schema
db.open().then(()=>{
  return isDeclaredSchemaSameAsInstalled(db);
}).then(areEqual => {
  if (!areEqual) return db.delete().then(()=>db.open());
}).then(()=>{
  // ...start application
});

```

**Comment by stutrek** [comment]
I had to make some small changes to get it to work. Subtracting on a string doesn't return what you want it to, and the sort was in the wrong spot.

```javascript
function getCanonicalComparableSchema(db) {
    return JSON.stringify(
        db.tables
            .map(({ name, schema }) => ({
                name,
                schema: [schema.primKey.src, ...schema.indexes.map(idx => idx.src).sort()].join(
                    ','
                ),
            }))
            .sort((a, b) => (a.name < b.name ? 1 : -1))
    );
}

function isDeclaredSchemaSameAsInstalled(db) {
    const declaredSchema = getCanonicalComparableSchema(db);
    return new Dexie(db.name).open().then(dynDb => {
        const installedSchema = getCanonicalComparableSchema(dynDb);
        return declaredSchema === installedSchema;
    });
}
```

**Comment by dfahlander** [comment]
Thanks for fixing it!
