### ISSUE TITLE
Edge compound index: put object throws DataError

### ISSUE THREAD

**Issue by darkowic** [dfahlander/Dexie.js#957]
I am aware that Edge does not support compound indexes but in section https://dexie.org/docs/Compound-Index#browser-limitations is written:

> But if passing an object to Table.where() (as samplified multiple times on this page), the query will work on all browsers and only utilize the compound index if browser supports it, otherwise fallback to using a simple index

Is it possible to put an object with a compound key which is the primary key? Is it possible to do a similar workaround for browsers missing compound key support for `put` method?

My example schema:
```
slideThumbnail: '[slideId+editingId], slideId, projectSlug, editingId, [projectSlug+editingId]'
```

**Comment by dfahlander** [comment]
It's not possible to use a compound primary key in edge legacy version. It would be possible to workaround using a middleware that transforms key to a string and back + an add-on that changes the internal schema accordingly, but that's quite a lot of work for a browser that will soon be replaced with a chromium engine supporting the full indexeddb spec. I have also an unmaintained polyfill [idb-iegap](https://www.npmjs.com/package/idb-iegap) that does polyfill this on the indexeddb layer, which turned out to be way more complex than it would be to write it as a dexie middleware + addon. I can't promise any reliability of the polyfill though as I haven't used it for years...

**Comment by darkowic** [comment]
Thanks for the answer!

**Comment by darkowic** [comment]
Btw are you using https://github.com/axemclion/IndexedDBShim (you have mentioned it in the idb-iegap)?  Looks like they are supporting compound index polyfill.

**Comment by dfahlander** [comment]
Indexeddbshim used to do that in an earlier version. Not anymore though as I've understood.
